[[commentary]]
quote='''
Surely it is better to merit a reward than to serve as a steward. Let us not be bound by the yoke of slavery, but let us serve in charity of spirit.
'''
source_url=''
source_title="LETTER 47"
uuid = "4e2f26d0-a61d-4380-82ce-e4db59e4d1f4"
