default_year=397
wiki='https://en.wikipedia.org/wiki/Ambrose'
uuid = "4a309ff8-2c25-4d64-84c6-a9c305005e0a"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/AmbroseOfMilan_(cropped).webp"
summary = "Ambrose of Milan, canonized as Saint Ambrose, was a theologian and statesman who served as Bishop of Milan from 374 to 397."
