default_year=446
wiki='https://en.wikipedia.org/wiki/Theodotus_of_Ancyra_(bishop)'
uuid = "97620772-7a04-411c-8371-dc4f4c2e6d47"
category = "Eastern & Byzantine Theology"
summary = "Theodotus of Ancyra was a fifth-century bishop of Ancyra. He was a theologian who attended the Council of Ephesus in 431, during the reign of Byzantine Emperor Theodosius II. Although he had earlier supported the Nestorian theology of Nestorius, bishop of Constantinople, Theodotus at the council supported Patriarch Cyril of Alexandria in condemning Nestorius. Theodotus was condemned in turn by the Nestorians at their 432 Synod of Tarsus."
