[[commentary]]
quote='''
Those, furthermore, who commit those sins whereof the apostle says, "They who do such things shall not inherit the kingdom of God"
'''
uuid = "1e6f371c-f116-4085-9294-7239a7f0e985"
