default_year=250
wiki='https://en.wikipedia.org/wiki/Pope_Fabian'
uuid = "a92a0d70-c387-4039-9ba5-73d6defa674b"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/5/51/Saints_Fabian_and_Sebastian_-_Giovanni_di_Paolo.png"
summary = "Pope Fabian was the bishop of Rome and head of the Catholic Church from 10 January 236 until his death on 20 January 250, succeeding Anterus. A dove is said to have descended on his head to mark him as the Holy Spirit's unexpected choice to become the next pope. He was succeeded by Cornelius."
