default_year=450
wiki='https://en.wikipedia.org/wiki/Isidore_of_Pelusium'
uuid = "e88d3b80-53f2-463c-887b-b03e40c5566e"
category = "Eastern & Byzantine Theology"
image = "https://download.biblians.com/commentaries/fathers/Isidore_of_Pelusium.webp"
summary = "Isidore of Pelusium was born in Egypt to a prominent Alexandrian family. He became an ascetic, and moved to a mountain near the city of Pelusium, in the tradition of the Desert Fathers."
