default_year=450
wiki='https://en.wikipedia.org/wiki/Isidore_of_Pelusium'
uuid = "3bce3510-bd01-4b61-b670-c51b731061e1"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/1/13/Isidore_of_Pelusium.jpg"
summary = "Isidore of Pelusium was born in Egypt to a prominent Alexandrian family. He became an ascetic, and moved to a mountain near the city of Pelusium, in the tradition of the Desert Fathers."
