default_year=264
wiki='https://en.wikipedia.org/wiki/Pope_Dionysius_of_Alexandria'
uuid = "c72a2c9c-8024-4a26-82ee-bdcf522c4779"
category = "Early Fathers (Pre-Nicaea)"
image = "https://download.biblians.com/commentaries/fathers/Dionisii_alek.webp"
summary = "Dionysius the Great was the 14th Pope and Patriarch of Alexandria from 28 December 248 until his death on 22 March 264. Most information known about him comes from a large corpus of correspondence. Only one complete letter survives; the remaining letters are excerpted in the works of Eusebius."
