[[commentary]]
quote='''
Let us too do this, meditating continuously on the things of God, and by means of the Lord's law, let our wills be grafted on to him.
'''
source_url=''
source_title="BOOK OF PERFECTION 61"
uuid = "5297b2fe-ec61-43c2-8306-c8551e175839"
