default_year=254
wiki='https://en.wikipedia.org/wiki/Faustinus_of_Lyon'
uuid = "504926ad-e690-4a35-b6a3-df7cb2a36426"
category = "Early Fathers (Pre-Nicaea)"
summary = "Faustin was the fifth bishop of Lyon. He is venerated as a saint within the Catholic Church."
