default_year=380
wiki='https://en.wikipedia.org/wiki/Orsisius'
uuid = "381aeb1b-59d6-462a-8ad5-c1521459b8d8"
category = "Syriac & Oriental Theology"
summary = "Orsisius was an Egyptian monk and author in the fourth century. His memorial is June 15."
