default_year=606
wiki='https://en.wikipedia.org/wiki/Paterius'
uuid = "aedd9a42-7527-4caf-a0a1-cd8ecb4766ef"
category = "Western & Medieval Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Museo_di_Santa_Giulia_Coro_delle_Monache_sarcofago_Brescia.jpg/3840px-Museo_di_Santa_Giulia_Coro_delle_Monache_sarcofago_Brescia.jpg"
summary = "Paterius was a bishop of Brescia. He is known as a compiler, in particular of works of Pope Gregory I, for whom he had worked as a notary."
