[[commentary]]
quote='''
If Paul and Apollos counted for nothing, what can we say about those who glory in the flesh?
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 3"
uuid = "87d23d06-f43f-44e9-88c1-2b0c328cc78d"
