[[commentary]]
quote='''
Gold, silver and precious stones will survive the fire of judgment, but wood, hay and straw will be burned up.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 3"
uuid = "885165ea-7ddd-4d7b-9f3b-da1c900abb54"
