[[commentary]]
quote='''
The Jews want signs, because that is what the prophets gave them, but even then they do not believe. The Greeks, on the other hand, want clever academic arguments.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 1"
uuid = "f4aefd8b-073a-41cd-8595-f6ccb522437a"
