[[commentary]]
quote='''
The one depends on the other. Either you believe both, or you believe neither.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 15"
uuid = "8b837ef4-68f3-4009-a415-7fdbb14a5787"
