[[commentary]]
quote='''
Paul points out that he and Apollos are merely hired hands on someone else's farm. They have nothing apart from the payment they get for their labor.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 3"
uuid = "88b2424d-9af1-4dec-91ff-91ed5d64f8e3"
