[[commentary]]
quote='''
The unbeliever is convicted when his conscience is struck by the teaching being given.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 14"
uuid = "883a358c-953a-4ef6-83c8-ad31236bea4a"
