[[commentary]]
quote='''
We have the mind of Christ because we have the Holy Spirit.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 2"
uuid = "1c9a940b-8949-47c5-b424-dfb4fd30773c"
