[[commentary]]
quote='''
Here Paul explains what he said above, which is that a believer should be a blessing to everyone.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 14"
uuid = "41e2acac-c066-4b39-b1bb-cc91f3fc3593"
