[[commentary]]
quote='''
Good teachers are accustomed to locate every hope and joy and crown in the progress of their students.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON THE FIRST LETTER TO THE THESSALONIANS"
uuid = "916b7418-14d4-4ffc-a3c7-8a6abe0e3458"
