[[commentary]]
quote='''
Paul is telling the Corinthians that if he had more to give them, he would be bound to do so, as a loving parent.
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 12"
uuid = "f6349815-2184-4e02-b7b2-565e6580ad35"
