[[commentary]]
quote='''
Our groanings are like those of a woman in labor, awaiting a new birth.
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 5"
uuid = "3195ed23-fba1-4ac0-af3b-c14f3f089b23"
