[[commentary]]
quote='''
Paul wants to show that he is especially anxious to save the Jews. As long as he is in the body he will honor his ministry, striving to save many of them by his example.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "9d5b6a75-5aed-4013-9e1c-e4a18d5ce236"
