[[commentary]]
quote='''
Previously nobody knew it, but at the time of writing Paul certainly knew it, as he indicated to others when he said: "We have the mind of the Lord."
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "75ec8fbc-f62a-4fe0-a470-841a54173150"
