[[commentary]]
quote='''
I will avenge the wrong, says the Lord, as my own, not as yours.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "b8d8b110-4047-425f-a904-4f7aed2a2d00"
