[[commentary]]
quote='''
Israel as a whole has not obtained righteousness because it did not seek it by faith but thought that it was justified solely by works of the law, even though it disregarded the greatest commandments of the law. That is why the Savior censures those who strain at a gnat but swallow a camel.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "c561f9bb-5945-40cb-9476-8851f1adf62c"
