[[commentary]]
quote='''
Who has done something beforehand, so that instead of magnifying God's mercy, he boasts that he has received what he deserved?
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "0c156e09-b580-4be8-8f69-66215343d38d"
