[[commentary]]
quote='''
Paul says that he died because then he transgressed knowingly. The commandment which would have led to life had it been kept in fact led to death, because it was disregarded.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "6545ee24-0bb0-4676-8d03-7802baa5969e"
