[[commentary]]
quote='''
Abraham's faith was so great that his earlier sins were all forgiven him, and righteousness was counted as credit for every one of them by faith alone. Later he was on fire with such love for God that he piled one good work on top of another. Therefore he has glory in God's eyes.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "76b74abe-7a7f-49f2-a110-676b9cb85151"
