[[commentary]]
quote='''
Christ alone should be seen in us, not the old self, for "one who says he abides in Christ should walk as he walked."
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "d62ffc64-9e10-4c73-b3fc-21eeeb73714a"
