[[commentary]]
quote='''
Now we must see whether circumcision is born of righteousness or righteousness of circumcision. It must be the former, because Abraham was righteous before he was circumcised.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "f8cbaf0e-62c6-4909-95a4-e82f3a775bbf"
