[[commentary]]
quote='''
The "work of God" means "a human being, created by God." Paul repeats what he said above [in verse 14], lest it appear that he is condemning creation. What is clean in itself becomes wrong if someone else takes offense on his account.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "d5bc96df-4529-40d3-b5ef-9c2759d62a64"
