[[commentary]]
quote='''
Here Paul shows that the people who came afterward belonged to the promise after the manner of Isaac.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "8bfba278-fee3-416c-900c-3f652a09dde3"
