[[commentary]]
quote='''
Even alms can be called a due. Revenue is ours to give to those who are passing by or to those who are seated by the roadside while we pass by.… Fear as well as honor must be given to those who are your superiors but only honor to your peers.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "58543d36-007e-4070-ba7e-7b1c44e206ec"
