[[commentary]]
quote='''
This was because Abraham believed so completely and so steadfastly.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "92cb1b8a-9221-4892-b7db-78cd4e732234"
