[[commentary]]
quote='''
Paul wants the baptized person to be steadfast and virtually perfect.
'''
source_url=''
source_title="PELAGIUS'S COMMENTARY ON ROMANS"
uuid = "0ba2052c-a5bc-41af-80e5-18f5023d825f"
