[[commentary]]
quote='''
For this is the spiritual victim which has abolished the pristine sacrifices.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Prayer.html"
source_title="On Prayer"
uuid = "b76cdba2-b199-46ea-a3b8-42860723404b"
