[[commentary]]
quote='''
But what reason is there in going to prayer with hands indeed washed, but the spirit has become fouled?—inasmuch as to our hands themselves spiritual cleansing is necessary, that they may be "lifted up pure" from falsehood, from murder, from cruelty, from poisonings, from idolatry and all the other blemishes which, conceived by the spirit, are effected by the operation of the hands.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Prayer.html'
source_title="ON PRAYER 13"
uuid = "487230dd-3902-4d17-aa4b-0504f21cd35a"

[[commentary]]
quote='''
Shall it be granted possible for human ingenuity to summon a spirit into water, and, by the application of hands from above, to animate their union into one body with another spirit of so clear sound; and shall it not be possible for God, in the case of His own organ, to produce, by means of "holy hands," a sublime spiritual modulation? But this, as well as the former, is derived from the old sacramental rite in which Jacob blessed his grandsons, born of Joseph, Ephrem and Manasses; with his hands laid on them and interchanged, and indeed so transversely slanted one over the other, that, by delineating Christ, they even portended the future benediction into Christ.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Baptism.html"
source_title="On Baptism"
uuid = "0149b0c5-e708-4e49-ac97-02c017657633"

[[commentary]]
quote='''
But what reason is there in going to prayer with hands indeed washed, but the spirit foul?-inasmuch as to our hands themselves spiritual purities are necessary, that they may be "lifted up pure" from falsehood, from murder, from cruelty, from poisonings, from idolatry, and all the other blemishes which, conceived by the spirit, are effected by the operation of the hands.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Prayer.html"
source_title="On Prayer"
uuid = "5cbef54b-78e9-492b-a2b0-4e5dc61e9711"

[[commentary]]
quote='''
Touching times of prayer nothing at all has been prescribed, except clearly "to pray at every time and every place."
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Prayer.html"
source_title="On Prayer"
uuid = "e2123ee8-bb6e-4baa-8458-482e00cee5e4"
