
[[commentary]]
quote='''
Just as they carefully prepared their will and testament, and committed it to a trust, and adjured (the trustees to be faithful to their charge), even so do I hold it.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FThe%2520Prescription%2520Against%2520Heretics.html"
source_title="The Prescription Against Heretics"
uuid = "00155fa3-5cad-4dd6-b608-29349bea08ee"
