
[[commentary]]
quote='''
For they both raised the dead, which God alone (can do), and restored the debilitated to their integrity, which none but Christ (can do); nay, they inflicted plagues too, which Christ would not do.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Modesty.html"
source_title="On Modesty"
uuid = "1f4b8920-43f7-45da-9dab-73ffc51e93be"
