[[commentary]]
quote='''
We are not washed in order that we may cease sinning, but because we have ceased, since in heart we have been bathed already.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Repentance.html'
source_title="On Repentance"
uuid = "ba7eb558-85a6-493b-b25b-f8fa293b5db5"

[[commentary]]
quote='''
But the Jewish Israel bathes daily, because he is daily being defiled: and, for fear that defilement should be practised among us also, therefore was the definition touching the one bathing made.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Baptism.html'
source_title="On Baptism"
uuid = "ea9072c0-43af-4a98-bee8-739418129534"
