[[commentary]]
quote='''
For He was from the native soil of Bethlehem, and from the house of David; as, among the Romans, Mary is described in the census, of whom is born Christ.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FAn%2520Answer%2520to%2520the%2520Jews.html"
source_title="An Answer to the Jews"
uuid = "2793b990-7f0c-4045-a249-6c78d324f5ee"

[[commentary]]
quote='''
"Away," says he, "with that eternal plaguey taxing of Caesar, and the scanty inn, and the squalid swaddling-clothes, and the hard stable. We do not care a jot for that multitude of the heavenly host which praised their Lord at night.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520the%2520Flesh%2520of%2520Christ.html"
source_title="On the Flesh of Christ"
uuid = "382625e8-4ab9-44b1-8e2a-2f9b23a85596"
