[[commentary]]
quote='''
Sodom also, and Gomorrah, would have escaped if they had fasted. This remedy even Ahab acknowledges.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Fasting.html"
source_title="On Fasting"
uuid = "e999ee13-cd60-4f73-a135-e3d1f2e43292"
