
[[commentary]]
quote='''
We have faith for a defence, if we are not smitten with distrust itself also, in immediately making the sign and adjuring, and besmearing the heel with the beast.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FScorpiace.html"
source_title="Scorpiace"
uuid = "7123b692-abd8-4355-9de3-02c48e3eae29"
