
[[commentary]]
quote='''
Sodom also, and Gomorrah, would have escaped if they had fasted. This remedy even Ahab acknowledges.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Fasting.html"
source_title="On Fasting"
uuid = "e7fa2345-d8f6-49b5-b8cb-4b1066591079"
