
[[commentary]]
quote='''
He has power to ask, if He will, legions of angels from the Father for His help. He exclaims that God had forsaken Him.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FAgainst%2520Praxeas.html"
source_title="Against Praxeas"
uuid = "1f1a6757-50bb-4284-a52d-bce13ecf2df9"
