
[[commentary]]
quote='''
Why not? He had found the son whom he had lost; he had felt him to be all the dearer of whom he had made a gain. Who is that father to be understood by us to be? God, surely: no one is so truly a Father; no one so rich in paternal love.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Repentance.html"
source_title="On Repentance"
uuid = "23e10975-e897-4a0c-8d34-d0abd53f9dd0"

[[commentary]]
quote='''
However, our Lord very frequently proclaimed God as a Father to us; nay, even gave a precept "that we call no one on earth father, but the Father whom we have in the heavens: and so, in thus praying, we are likewise obeying the precept.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Prayer.html"
source_title="On Prayer"
uuid = "e8e3f198-40b6-4ea1-ad5d-1999bb9c8588"

[[commentary]]
quote='''
To Abraham, in fine, they appeal; prohibited though they are to acknowledge any other father than God. Grant, now, that Abraham is our father; grant, too, that Paul is.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Monogamy.html"
source_title="On Monogamy"
uuid = "a5e7391b-6e14-4816-a011-10954af847ed"
