
[[commentary]]
quote='''
"But the fearful," says John-and then come the others-" will have their part in the lake of fire and brimstone." Thus fear, which, as stated in his epistle, love drives out, has punishment.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FScorpiace.html"
source_title="Scorpiace"
uuid = "4493dc60-548a-46b1-aef6-583a89bef895"

[[commentary]]
quote='''
In short, this Apocalypse, in its later passages, has assigned "the infamous and fornicators," as well as "the cowardly, and unbelieving, and murderers, and sorcerers, and idolaters," who have been guilty of any such crime while professing the faith, to "the lake of fire," without any conditional condemnation.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Modesty.html"
source_title="On Modesty"
uuid = "2e7c7774-297a-45bd-a234-96bb38b44850"

[[commentary]]
quote='''
Last of all, in the Revelation, He does not propose flight to the "fearful," but a miserable portion among the rest of the outcast, in the lake of brimstone and fire, which is the second death.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FOn%2520Flight%2520in%2520Persecution.html"
source_title="On Flight in Persecution"
uuid = "0112381d-20a3-406f-82ee-91362e0aae21"
