
[[commentary]]
quote='''
When Paul asserts that males and females changed among themselves the natural use of the creature into that which is unnatural, he validates the natural way.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Tertullian%2FThe%2520Chaplet%252C%2520or%2520De%2520Corona.html'
source_title="THE CHAPLET 6"
uuid = "4730f945-b71b-4d45-bd9d-2c697ffdc371"

[[commentary]]
quote='''
Yes, and also in the first chapter of the epistle he authenticates nature, when he asserts that males and females changed among themselves the natural use of the creature into that which is unnatural, by way of penal retribution for their error.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Tertullian%2FThe%2520Chaplet%252C%2520or%2520De%2520Corona.html"
source_title="De Corona"
uuid = "2b354c68-b80e-40df-8e51-d2a8765af58e"
