[[commentary]]
quote='''
By "milk" Paul means moral teaching and miracles. Solid food, by contrast, is the proclamation of the doctrines of God.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "879bce37-96c1-438f-839b-c044f3d1de1e"
