[[commentary]]
quote='''
The fornicator is also guilty of impiety, for by doing harm to his body he has corrupted the temple of the Holy Spirit.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "ff3276f9-01b2-4f45-a9f0-2f84cf4212cf"
