[[commentary]]
quote='''
The person who speaks in the Holy Spirit speaks when he chooses to do so and then can be silent, like the prophets. But those who are possessed by an unclean spirit speak even when they do not want to. They say things that they do not understand.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "6fe33fc9-e718-4f7b-b08e-d34ac6123ce0"
