[[commentary]]
quote='''
There is no language without meaning because all languages are human.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "09631011-5764-4972-8886-c339f7f6ab24"
