[[commentary]]
quote='''
Paul did not mean that a woman should marry an unbeliever, only that she should stay with him if she is already married.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "3d39bafc-fa50-4b60-82dd-9b8c6aa9b857"
