[[commentary]]
quote='''
It is veiled only to those who are unbelievers. It is not hidden from everyone, as the face of Moses was hidden from all Israel in the Old Testament..
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "2168d1b0-6029-42a0-8aed-316c37fd85c2"
