[[commentary]]
quote='''
The purpose and view of the epistle is here, as Paul mentions, to respond to the emphasis on angels urged by some. Christ is the head of all, just as the soul is the head of the body. Christ is head of all the cosmic elements. It makes no sense to be in submission to anything else. .
'''
uuid = "e9408074-ac18-40a2-8c5a-e631c4bcda26"
