[[commentary]]
quote='''
The gospel has come not only to the Colossians, but to the whole world, where it is powerful and grows by means of the preached word. .
'''
uuid = "f9ed2948-853b-4143-a236-7370ae6c6fd6"
