[[commentary]]
quote='''
He says, "division of soul and spirit." The soul has a special feeling for the body, but the grace of the Holy Spirit draws against the body to the heavenly things.
'''
source_url=''
source_title="FRAGMENTS ON THE EPISTLE TO THE HEBREWS 4.12"
uuid = "69cfa905-0737-4949-8e22-61b4890ef56f"
