[[commentary]]
quote='''
This does not mean that Christ is a part of the law but rather that he is the beginning of a new life. The law has come to an end; it has ceased.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "a410d122-14ec-44bc-a85c-8b5e08c41a06"
