default_year=1089
wiki='https://en.wikipedia.org/wiki/Lanfranc'
uuid = "4ab25ca1-5b45-4553-aca4-1c877d9b40ed"
category = "Western & Medieval Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/c/c8/Lanfrancstatuecanterburycathedraloutside.jpg"
summary = "Lanfranc was an Italian-born English churchman, monk and scholar. Born in Italy, he moved to Normandy to become a Benedictine monk at Bec. He served successively as prior of Bec Abbey and abbot of St Stephen's Abbey in Caen, Normandy and then as Archbishop of Canterbury in England, following its conquest by William the Conqueror. He is also variously known as Lanfranc of Pavia, Lanfranc of Bec, and Lanfranc of Canterbury. In his lifetime, he was regarded as the greatest theologian of his generation."
