[[commentary]]
quote='''
None would expect anything else, implies Paul, once again showing how important the matter was.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 192"
uuid = "f93902b0-02f2-4df9-afa6-4803113f8db8"
