[[commentary]]
quote='''
These gifts were given to women as well as men, as the Acts of the Apostles makes plain.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 245"
uuid = "cc06ebfc-07a0-472b-ae74-e604f2593a62"
