[[commentary]]
quote='''
Love always remains firm and stable, unchanged and unchanging.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 254"
uuid = "acc3f070-4c69-4a80-be1f-2ba4427e96bd"
