[[commentary]]
quote='''
Here Paul recalls the words of the Lord [in Matthew 5:32]: "Whoever puts away his wife, except for fornication, makes her an adulteress."
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE OF PAUL TO THE CORINTHIANS 204"
uuid = "3e0a3da7-6dd5-4f09-828f-8561511b82a1"
