[[commentary]]
quote='''
Whoever has received the revelation of the Spirit has also received the Spirit's understanding.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 177"
uuid = "a4d4ff76-e50e-4082-a868-3e78e988cbeb"
