[[commentary]]
quote='''
The unspiritual man is one who is happy enough with his own ideas and who neither accepts nor understands the teaching of the Spirit.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 178"
uuid = "881d8e69-fb79-4fe7-b98f-cf75b9156012"
