[[commentary]]
quote='''
If I am unable to judge myself, how shall I presume to judge others?
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 187"
uuid = "994e52b3-1a6e-475d-8fff-28b9ae9a3d50"
