[[commentary]]
quote='''
Paul magnifies the accusation in order to prevent people from committing the crime.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 217"
uuid = "64b53aaa-3317-48b1-805b-1b0b9e3e799e"
