[[commentary]]
quote='''
Note that Paul does not say that a woman who contracts a second marriage will be unhappy. Rather he says that she will be happier if she remains single. It is all a matter of degree.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST EPISTLE TO THE CORINTHIANS 212"
uuid = "12fd1b6f-2990-48c8-a8bd-1d8c91037656"
