[[commentary]]
quote='''
It is not nature but faith that has made Timothy a son.
'''
source_url=''
source_title="INTERPRETATION OF THE FIRST LETTER TO TIMOTHY"
uuid = "4c440c82-6697-44cd-8c84-c92b42e7ef8a"
