[[commentary]]
quote='''
"Consciences seared" refers to their final numbing, the deadening of their consciences.
'''
source_url=''
source_title="INTERPRETATION OF THE FIRST LETTER TO TIMOTHY"
uuid = "d3067664-f546-4557-b09d-c3b5b52a505e"
