[[commentary]]
quote='''
Paul had to do battle not only with external foes but also with enemies within the fellowship of the church. He was afraid that believers would be turned away to harmful things.
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 323"
uuid = "1ef9857d-ceb4-4a51-b5ea-b03fa6302ccf"
