[[commentary]]
quote='''
Christ was called what we are in order to call us to be what he is.
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 318"
uuid = "9045b2e3-fde7-41f6-9635-e69c4cc495eb"
