[[commentary]]
quote='''
Paul backs his exhortation up with this prophetic testimony.
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 318"
uuid = "3e069088-027a-47bd-8bd3-9b75d42bfc74"
