[[commentary]]
quote='''
Although we are surrounded by the world, we do not give in to it.
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 337"
uuid = "7e46b882-9e97-4f5f-8b49-e5b4d6767886"
