[[commentary]]
quote='''
Christ himself teaches us that God is his Father..
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 289"
uuid = "157e64b4-badf-4476-ac6a-bb575b4815ef"
