[[commentary]]
quote='''
It is Paul's custom to praise God every time he expounds some divine dispensation or other.
'''
source_url=''
source_title="COMMENTARY ON THE SECOND EPISTLE TO THE CORINTHIANS 336"
uuid = "1f645dc2-15de-4fb2-a81f-049b9073d303"
