[[commentary]]
quote='''
When, as we have already mentioned, Alexander joined together the whole known world, so to speak, into his kingdom and then suffered the fate common to all humankind, the kingdom was divided into four parts.
'''
source_url=''
source_title="COMMENTARY ON DANIEL 11:3-4:13"
uuid = "c61a1d5f-cdf9-4eeb-a527-80c13fc48b4a"


[[commentary]]
quote='''
He does not spend much time on the ruler of Asia Minor or Macedonia, especially since no grief befell the Jews through them. He mentions only the two through whom the Jews would be tested with grievous misfortunes. These are the king of Egypt and the one entrusted with the rule of the nations that lay to the east. The latter held palaces in both Antioch and Babylon.
'''
source_url=''
source_title="COMMENTARY ON DANIEL 11:3-4"
uuid = "b4ba54c5-c87b-402c-95ca-8da395bc498a"
