[[commentary]]
quote='''
Nothing will be an obstacle to him; instead, he will do what he wishes. Of such people blessed David says in exhortation, "Do not vie with the one who prospers in his way, with the one who commits lawlessness": it often happens that people living a godless and lawless life prosper considerably in their lawless pursuits.
'''
source_url=''
source_title="COMMENTARY ON DANIEL 8:24-25"
uuid = "4adcc420-3f1a-4c09-9f1f-e4ef064b6c2d"
