[[commentary]]
quote='''
Here he clearly shows the distinction between apostolic and prophetic labors. Prophets have committed to them the responsibility of only one race, from which they were to have arisen and whose native language they knew. Apostles … have all the nations and peoples of the world entrusted to them, according to the command of the Lord.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 1:3"
uuid = "fb338792-9e34-4f0c-9f0e-71245daf257a"
