[[commentary]]
quote='''
The phrase "he is still speaking" means, To this day he is famous and celebrated and enjoys a good name among all religious people.
'''
source_url=''
source_title="INTERPRETATION OF HEBREWS 11"
uuid = "181da220-8544-4a1b-913f-e39e6fb8d7ce"
