[[commentary]]
quote='''
So let us despise things of this life and look forward to those that are stable and permanent.
'''
source_url=''
source_title="INTERPRETATION OF HEBREWS 13"
uuid = "64ea4ca9-2615-43c0-9b67-a33fa5dc8876"
