[[commentary]]
quote='''
He completely destroyed the force of sin, promising us immortality; sin is incapable of proving a problem to immortal bodies.
'''
source_url=''
source_title="INTERPRETATION OF HEBREWS 9"
uuid = "879c3efa-a866-46d3-9a2c-425d2a387cf9"
