[[commentary]]
quote='''
As God has no one superior to him (he is saying), his oath was witness; he swore by himself, in fact.
'''
source_url=''
source_title="INTERPRETATION OF HEBREWS 6"
uuid = "f2d71630-48c6-4ade-aaeb-8f4e17b93de2"
