[[commentary]]
quote='''
Isaiah calls the kings and the leaders the heads and the priests and teachers the heart. For what the heart is to the body, the priests and teachers are for the people, and what the head is for the body, the kings and leaders are for their subjects.
'''
source_url=''
source_title="COMMENTARY ON ISAIAH 1:5"
uuid = "80f55447-952d-40d7-aa9e-8adb5787a6cd"
