[[commentary]]
quote='''
This is precisely what he also says about the priests and the Levites, noting that their line will be compared with the host of heaven and the sand of the sea. The facts confirm what is said: the whole land and sea are full of high priests and the deacons performing the liturgy of the Levites.
'''
source_url=''
source_title="ON JEREMIAH 7:33.18"
uuid = "11cd6dbe-a1e8-41ac-8e71-646df4e9f532"
