[[commentary]]
quote='''
He refers to the kings and priests as [stupid] shepherds because they were the guardians of this wandering people. 
'''
source_url=''
source_title="On JEREMIAH 3:10"
uuid = "cce51ed0-f605-4a8a-90c1-8706e0e87907"
