[[commentary]]
quote='''
Jeremiah said, "Now that matters have proven the truthfulness of my prophecy and the falsehood of your prophets, you must now judge rightly and punish those who lied, not him who warned you of the truth beforehand." Then he asked to be released from the house of the scribe.
'''
source_url=''
source_title="ON JEREMIAH 8:37"
uuid = "90aea4c2-fc18-47ad-951e-066e79c07b97"
