[[commentary]]
quote='''
This is how we should think about the crowns laid up for us. For even if we do not perceive exactly what these are like, we ought at least to know that God, as Master of the contest, will reveal this to us.
'''
source_url=''
source_title="EPISTLE TO THE PHILIPPIANS 3.15"
uuid = "04798339-ba6d-42ca-8e04-6ea24e7a7a44"
