[[commentary]]
quote='''
When he says you, he means all the faithful.… And he says this to work on their souls and to teach them that his martyrdom is so great that it has the character of a libation and a sacrifice.
'''
source_url=''
source_title="EPISTLE TO THE PHILIPPIANS 2.17"
uuid = "0a323538-99ec-4a9a-b547-59264192adb2"
