[[commentary]]
quote='''
Now, he says this not by way of accusation but out of a longing for help. When will you appear, he is saying, and assist the wronged?… Render my soul proof against their machinations.
'''
source_url=''
source_title="COMMENTARY ON THE PSALMS 35:9"
uuid = "bc8be353-6836-41a5-82ab-ef1bb2e9cff2"
