[[commentary]]
quote='''
Now, the verse forecasts the voice emanating from heaven at the Jordan, "This is my Son, the Beloved, in whom I am well pleased." He called it "thunder" as coursing to the whole world through the sacred Gospels.
'''
source_url=''
source_title="COMMENTARY ON THE PSALMS 29:4"
uuid = "1e77cb64-de44-488b-b753-b502c37b2893"
