[[commentary]]
quote='''
Even if you see one choosing wickedness and not deviating from his purpose but being borne downstream, do not be worried and concerned that no one is in control of the world.
'''
source_url=''
source_title="COMMENTARY ON THE PSALMS 37:3"
uuid = "80f2b1ba-86af-4409-b432-355c051043e4"
