[[commentary]]
quote='''
He will build a world that is inundated with the torrent of iniquity, will restore it and will make it a new creation. Hence blessed Paul also cries aloud, "If anyone is in Christ, he is a new creation."
'''
source_url=''
source_title="COMMENTARY ON THE PSALMS 29:9"
uuid = "70e381c7-ea02-42e9-ac74-514125b774b6"
