[[commentary]]
quote='''
When Paul says "as far round as Illyricum," he means that he got to Illyricum in a roundabout way, via the eastern provinces, the Black Sea region, Asia Minor and Thrace.
'''
source_url=''
source_title="INTERPRETATION OF THE LETTER TO THE ROMANS"
uuid = "15e8b6a4-4f43-44c2-a39a-a0b35d93ff7e"
