[[commentary]]
quote='''
God did not promise eternal life to those who worshiped idols but to those who even apart from the law led a Mosaic life, embraced godliness and the worship of God, and were concerned about righteousness.
'''
source_url=''
source_title="INTERPRETATION OF THE LETTER TO THE ROMANS"
uuid = "eaf2cffa-7f5a-4db6-a9bb-66b9c00aac34"
