[[commentary]]
quote='''
Paul praises Urbanus more highly than Stachys, because Urbanus had helped him in his preaching and in his struggles.
'''
source_url=''
source_title="INTERPRETATION OF THE LETTER TO THE ROMANS"
uuid = "a14f5619-70c2-4c5f-a7b1-6cc69d330243"
