[[commentary]]
quote='''
This was not the intention of the apostles' teaching. On the contrary, they demanded that everyone abstain from all manner of wickedness.
'''
source_url=''
source_title="INTERPRETATION OF THE LETTER TO THE ROMANS"
uuid = "ef6caa0e-9856-48d2-8906-54b304aca657"
