[[commentary]]
quote='''
This is no small praise, for Paul says that he is "beloved in the Lord," because he behaved uprightly and honestly.
'''
source_url=''
source_title="INTERPRETATION OF THE LETTER TO THE ROMANS"
uuid = "f9ee104d-0768-463a-9219-5dd8aceccb33"
