[[commentary]]
quote='''
The weak were those who continued to observe the law.
'''
source_url=''
source_title="INTERPRETATION OF THE LETTER TO THE ROMANS"
uuid = "8e04cb84-9f14-40e7-9147-bd1d3c53ee13"
