[[commentary]]
quote='''
Paul says that "the law came in" because he wants to show that God did not leave earlier generations destitute of his providence. But he also gave the law to the Jews, so that by their zeal and dedication to godliness they could act as a light to the other nations.
'''
source_url=''
source_title="INTERPRETATION OF THE LETTER TO THE ROMANS"
uuid = "45e7a4a9-d20f-452d-a862-7e37ee4ace76"
