[[commentary]]
quote='''
And the young men came in, and found her dead, and, carrying her forth, buried her by her husband. And great fear came upon all the Church, and upon as many as heard these things."
'''
uuid = "e7a66850-8af6-495e-a3d3-012fca3f16fc"
