[[commentary]]
quote='''
Peter teaches briefly but clearly by the testimony of the prophets and the law that the Lord is to be listened to by the nations, and that he will surely condemn the unbelieving, but he will grant an eternal blessing to the faithful.
'''
uuid = "e647f5ff-016a-4386-8df9-b024ff9b19f5"
