default_year=379
wiki='https://en.wikipedia.org/wiki/Macrina_the_Younger'
uuid = "6c6b5deb-fa4b-47c6-8b6a-63dee3ff091a"
category = "Eastern & Byzantine Theology"
image = "https://download.biblians.com/commentaries/fathers/Macrina_the_Younger.webp"
summary = "Macrina the Younger was an early Christian consecrated virgin. Macrina was elder sister of Basil the Great, Gregory of Nyssa, Naucratius and Peter of Sebaste. Gregory of Nyssa wrote a work entitled Life of Macrina in which he describes her sanctity and asceticism throughout her life. Macrina lived a chaste and humble life, devoting her time to prayer and the spiritual education of her younger brother Peter."
