default_year=379
wiki='https://en.wikipedia.org/wiki/Macrina_the_Younger'
uuid = "1557b5b1-21b4-49ab-8278-a430142ec0d7"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/2/27/Macrina_the_Younger.jpg"
summary = "Macrina the Younger was an early Christian consecrated virgin. Macrina was elder sister of Basil the Great, Gregory of Nyssa, Naucratius and Peter of Sebaste. Gregory of Nyssa wrote a work entitled Life of Macrina in which he describes her sanctity and asceticism throughout her life. Macrina lived a chaste and humble life, devoting her time to prayer and the spiritual education of her younger brother Peter."
