[[commentary]]
quote='''
The person who hates is in darkness until he repents or until he discovers love.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 1 JOHN"
uuid = "38d1cf82-a3b3-4787-abfa-8ebcb71fa579"
