[[commentary]]
quote='''
God can never turn himself into a liar, because he is the essence of truth. But an unbelieving man is a liar, because he does not believe in the truth of God.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 1 JOHN"
uuid = "9f241043-3fe2-4fd2-9804-a33cb551c647"
