[[commentary]]
quote='''
Evil desires are called "carnal" because they operate through the flesh, but in reality they are spiritual, because they come from the soul.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 1 PETER"
uuid = "49c3d234-7f99-4e0c-9b8a-c6c819d59a14"
