[[commentary]]
quote='''
Everything in this prophecy is written about Christ. There are many living stones in God's temple, but here we are contemplating only the One.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 1 PETER"
uuid = "b819e247-df35-4675-bb3f-004cc7160f58"
