[[commentary]]
quote='''
As you have been born again by the Word of the living God, lay aside all malice, for an infant has no malice in him.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 1 PETER"
uuid = "0e192e16-b5b6-4c57-98c4-921d43c35e0f"
