[[commentary]]
quote='''
By "truth" John is referring to the Holy Spirit, because love is always the work of the Spirit.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 2 JOHN"
uuid = "42e6aaba-daf6-4f49-abc7-76af60c7ba82"
