[[commentary]]
quote='''
The one who received glory and honor was not inferior to the one who bestowed these things, because it was in his human flesh that the Son received them, not in his eternal divinity.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 2 PETER"
uuid = "2e1e037f-9e99-4bab-9146-aabd55bf97a4"
