[[commentary]]
quote='''
You are waiting for the end as the virgins waited for the bridegroom.
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 2 PETER"
uuid = "d12072ba-10a6-43f0-9b68-dce3186f89fa"
