[[commentary]]
quote='''
The right way is the way of Christ, who said: "I am the way, the truth and the life."
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON 2 PETER"
uuid = "439bffb1-9181-4b76-b617-3c4ac8c4c965"
