[[commentary]]
quote='''
The prayer of faith is the consensus of the whole church, as it is said in the Gospel: "Whatever you ask in my name shall be done for you."
'''
source_url=''
source_title="INTRODUCTORY TRACTATE ON THE LETTER OF JAMES"
uuid = "1c89ca0c-3007-425c-9d04-236a9bd75430"
