[[commentary]]
quote='''
Temptations can be endured by spiritual knowledge and faith in the Trinity.
'''
source_url=''
source_title="INTRODUCTORY TRACTATE ON THE LETTER OF JAMES"
uuid = "90cb5dd9-f91c-4ca8-903d-bad8f6cf896a"
