[[commentary]]
quote='''
It is true of course that gold does not rust, but James is comparing it to material things which do rust in the course of time.
'''
source_url=''
source_title="INTRODUCTORY TRACTATE ON THE LETTER OF JAMES"
uuid = "79b2693d-49b0-48b8-a667-dd1a4677ab3b"
