[[commentary]]
quote='''
The faith was first delivered to these people by the apostle Paul, who said: "No other foundation can anyone lay, than the one which is already laid."
'''
source_url=''
source_title="INTRODUCTORY COMMENTARY ON JUDE"
uuid = "2c448c2a-0644-46ab-a703-1a20b88bbe33"
