default_year=449
wiki='https://en.wikipedia.org/wiki/Hilary_of_Arles'
uuid = "0de51929-14ab-491d-a9d9-ca16b266d0ae"
category = "Western & Medieval Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/8/84/Hilari14.jpg"
summary = "Hilary of Arles, also known by his Latin name Hilarius, was a bishop of Arles in Southern France. He is venerated as a saint in the Eastern Orthodox Church and Roman Catholic Church, with 5 May being his feast day."
