default_year=400
wiki='https://en.wikipedia.org/wiki/Pseudo-Hegesippus'
uuid = "1128864c-fdfa-47c5-90b9-8ea1552deae9"
category = "Apocrypha, Documents & Liturgies"
summary = 'Pseudo-Hegesippus is the conventional name of the anonymous author of De excidio Hierosolymitano, a fourth-century Christian Latin adaptation of The Jewish War of Flavius Josephus. The text itself may also be referred to as "Pseudo-Hegesippus".'
