[[commentary]]
quote='''
Also, twelve stones from Jordan's bed,
Left dry when waters backward flowed,
He raised and firmly set in place,
The type of Christ's apostles twelve.
'''
source_url=''
source_title="HYMNS FOR EVERY DAY 177.180"
uuid = "b5b2f35a-09e5-43b0-9d4c-711bc44e0b39"
