[[commentary]]
quote='''
Water and blood flow out from the pierced sides of the Savior.
Blood indicates the victory, and water stands for baptism.
The two robbers on crosses on each side dispute with each other.
One denies Christ is God, but the other wins heavenly glory.
'''
source_url=''
source_title="SCENES FROM SACRED HISTORY 42"
uuid = "9a6b2d4b-d98c-4cc7-b89b-608e5c34c1fb"
