[[commentary]]
quote='''
Driven forth, the wily demons, legion named that evil scourge,
Seize upon the sordid foulness of a herd of filthy swine
And into the muddy waters plunge themselves with maddened beasts.
'''
source_url=''
source_title="HYMN 9"
uuid = "052c2100-0c27-4198-bac3-c9e16956442b"
