[[commentary]]
quote='''
This Wisdom uttered made the sky,
The sky and light and all besides;
All by the Word's almighty power
Were fashioned, for the Word was God.
'''
source_url=''
source_title="HYMNS FOR EVERY DAY 11"
uuid = "bca111b9-83c2-4784-bf7d-97a9078ac8df"
