[[commentary]]
quote='''
God raised up his Son and sent him first to you:
The Lord had come to his own and among his own, awaiting the first fruits of faith from those people he took his roots from. The others subsequently had to be saved by the preaching of the apostles.
'''
uuid = "4d5a8ac4-7d76-4d20-af0a-b74dcc69ba41"
