[[commentary]]
quote='''
the God of our fathers:
By mentioning the fathers he encourages belief, avoiding the appearance of introducing something new.
'''
uuid = "963ccbfc-96e2-49ab-a886-259110c766e0"
