[[commentary]]
quote='''
We also will be a rock, imitating, as far as possible in our changing nature, the unchanging and permanent nature of the Master.
'''
source_url=''
source_title="ON PERFECTION"
uuid = "fa3e9749-4a20-4555-9e73-11496c65ae8f"
