[[commentary]]
quote='''
James, under pressure to cut off Christ, his true head, was [physically] decapitated, yet the [true] head of every person is Christ according to the apostle and at the same time the head of the entire church.
'''
source_url=''
source_title="HOMILY 2 ON ST. STEPHEN"
uuid = "8f227c6c-076a-427f-be57-537869a1b9a2"
