[[commentary]]
quote='''
And he is also a "beginning." … But what benefits do we derive from believing that he is the beginning? We become ourselves what we believe our beginning to be. .
'''
uuid = "0f09e28d-8e71-45f8-bbfe-4077325f16b0"
