[[commentary]]
quote='''
What is the stone … but Christ? For of him Isaiah says, "And I am laying in Zion for a foundation, a costly stone, precious, elect"; and Daniel likewise, "A stone was cut out but not by hand," that is, Christ was born without a man.
'''
source_url=''
source_title="ON THE BAPTISM OF CHRIST"
uuid = "297f50e0-6f94-43d1-916b-d7781734637e"
