[[commentary]]
quote='''
"Rejoicing in these lacerations," Paul says, "I bear the marks of Christ in my own body." He readily yields to his weakness in all these misfortunes, through which the power of Christ is being perfected in virtue.
'''
source_url=''
source_title="ORATION 12 ON SONG OF SONGS 5.7"
uuid = "1c76000d-8d0a-4dbc-b56c-7048ac768b2c"
