default_year=395
wiki='https://en.wikipedia.org/wiki/Gregory_of_Nyssa'
uuid = "2714c221-4a63-427d-a3f6-22be4c35e1e0"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/2/29/Gregory_of_Nyssa.jpg"
summary = "Gregory of Nyssa, also known as Gregory Nyssen, was an early Christian theologian who served as the bishop of Nyssa from 372 to 376 and from 378 until his death in 394. He is venerated as a saint in Eastern Orthodoxy, the Catholic Church, Oriental Orthodox Churches, Anglicanism, and Lutheranism. Gregory, his elder brother Basil of Caesarea, and their friend Gregory of Nazianzus are collectively known as the Cappadocian Fathers."
