[[commentary]]
quote='''
Paul examined … the unclear and hidden aspects of the divine mysteries and through suggestive phrases revealed the illuminations which came to him from God concerning the understanding of what is incomprehensible and unsearchable.
'''
source_url=''
source_title="ON PERFECTION"
uuid = "6bebbf63-93c3-41e8-bef9-df25f51d1ce7"
