default_year=251
wiki='https://en.wikipedia.org/wiki/Alexander_of_Jerusalem'
uuid = "6f52ad4b-44d7-43d4-b19b-5594a0045010"
category = "Early Fathers"
image = "https://upload.wikimedia.org/wikipedia/commons/3/36/Alexander_of_Jerusalem.jpg"
summary = "Alexander of Jerusalem was a third century bishop who is venerated as a martyr and saint by the Eastern Orthodox Church, Oriental Orthodox churches, and the Roman Catholic Church. He died during the persecution of Emperor Decius."
