default_year=325
wiki='https://en.wikipedia.org/wiki/First_Council_of_Nicaea'
uuid = "de6d6700-4c68-4704-9e3e-3ca7e641d6d2"
category = "Apocrypha, Documents & Liturgies"
image = "https://upload.wikimedia.org/wikipedia/commons/1/1d/%CE%9C%CE%B9%CF%87%CE%B1%CE%AE%CE%BB_%CE%94%CE%B1%CE%BC%CE%B1%CF%83%CE%BA%CE%B7%CE%BD%CF%8C%CF%82_-_%CE%91%CE%84_%CE%9F%CE%B9%CE%BA%CE%BF%CF%85%CE%BC%CE%B5%CE%BD%CE%B9%CE%BA%CE%AE_%CE%A3%CF%8D%CE%BD%CE%BF%CE%B4%CE%BF%CF%82_7741.jpg"
summary = "The First Council of Nicaea was a council of Christian bishops convened in the Bithynian city of Nicaea by the Roman Emperor Constantine I, also known as the First Ecumenical Council. It met from May until the end of July 325."
