default_year=600
wiki='https://en.wikipedia.org/wiki/Apringius'
uuid = "b790ad16-be52-4c5c-ab61-ad5970ff90fd"
category = "Western & Medieval Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/4/40/Badajoz_-_Catedral_de_San_Juan_Bautista%2C_vidrieras_02.jpg"
summary = "Apringius of Beja was a sixth-century Latin Church Father who wrote a commentary on the Book of Revelation. Only fragments of his commentary survive."
