default_year=165
wiki='https://en.wikipedia.org/wiki/Justin_Martyr'
uuid = "bf314335-529d-4b59-b7bb-ffa08c415072"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/a/a7/Saint_Justin_Martyr_by_Theophanes_the_Cretan.jpg"
summary = "Justin Martyr, also known as Justin the Philosopher, was an early Christian apologist and philosopher. The First Apology, his most well-known text, passionately defends the morality of the Christian life and provides various arguments to convince the Roman emperor Antoninus Pius to abandon persecution of the Church. Justin also indicates that historical manifestations of the Logos predated Christ's incarnation, and that many historical Greek philosophers were unknowing Christians."
