[[commentary]]
quote='''
The fish which swallowed Jonah in the sea, shows forth the death which Christ suffered in the world. Three days and nights was the one in the whale's belly, the other in the tomb.
'''
uuid = "5749ce6a-bc39-4484-8226-0b27e8f6dc76"
