default_year=306
wiki='https://en.wikipedia.org/wiki/Phileas_and_Philoromus'
uuid = "c7dc97fe-2c4e-43e8-94db-ae1bc67a02c7"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Acts_of_Phileas_and_a_Greek_Psalter_%28CBL_BP_XV._f.4r%29.jpg/3840px-Acts_of_Phileas_and_a_Greek_Psalter_%28CBL_BP_XV._f.4r%29.jpg"
summary = "Saints Phileas and Philoromus were two Egyptian martyrs under the Emperor Diocletian. Phileas was Bishop of Thmuis and Philoromus was a senior imperial officer."
