default_year=250
wiki='https://en.wikipedia.org/wiki/Marcus_Minucius_Felix'
uuid = "04b50a8b-0fff-4247-8add-0dbe7ec5d388"
category = "Early Fathers (Pre-Nicaea)"
summary = "Marcus Minucius Felix was a Roman legal practitioner and one of the earliest Latin apologists for Christianity."
