[[commentary]]
quote='''
Neither need I say any thing about his pride and the haughtiness with which he assumed worldly dignities, and his wishing to be styled procurator
'''
uuid = "f36a5b42-eedf-4ad0-8be6-973633d89de4"
