[[commentary]]
quote='''
When writing to Timothy he put at the head of the letter, "To my dearly beloved son," for he had begotten him, not in body but in faith.
'''
source_url=''
source_title="EXPLANATION OF THE PSALMS 101.29"
uuid = "3bc364a2-110a-4bf3-9f1b-aac5845bf238"
