[[commentary]]
quote='''
Unity knows no number, equality allows no scale. As Scripture says, "You shall not go up by steps to my altar."
'''
source_url=''
source_title="EXPOSITION OF THE PSALMS 116:2"
uuid = "b1cefcca-73f3-4b34-a64f-a0ea192b1e54"
