[[commentary]]
quote='''
"Today" means always, for the one who gives us advice pertaining to salvation must always have our attention. The Apostle expressed the meaning of this word powerfully: "But encourage one another every day, as long as it is called 'today.' "
'''
source_url=''
source_title="EXPOSITION OF THE PSALMS 94.7"
uuid = "1cd5f86f-1c94-4541-85e3-d50ae6c3fe99"
