default_year=585
wiki='https://en.wikipedia.org/wiki/Cassiodorus'
uuid = "6a8eb4a2-b1bf-42cd-b162-f57359b6dccb"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/Gesta_Theodorici_-_Flavius_Magnus_Aurelius_Cassiodorus_(c_485_-_c_580).webp"
summary = "Magnus Aurelius Cassiodorus Senator, commonly known as Cassiodorus, was a Roman statesman, scholar, and writer who served in the administration of Theodoric the Great, king of the Ostrogoths. Senator was part of his surname, not his rank. In his later years, he devoted himself to Christian learning and founded the Vivarium monastery, where he worked extensively during the final decades of his life."
