[[commentary]]
quote='''
"I will hope in the Lord," in whom there is nothing empty, … but everything remains fixed and whole.
'''
source_url=''
source_title="EXPLANATION OF THE PSALMS 31:7"
uuid = "19802757-6445-4fd7-b1a5-a257cfae2fe2"
