[[commentary]]
quote='''
He points all things back to the one who has freely given them, not to himself who has received what was conferred on him.
'''
source_url=''
source_title="EXPLANATION OF THE PSALMS 16:2"
uuid = "e839058b-7d26-4bce-a722-931d7ac3b35b"
