[[commentary]]
quote='''
They are truly right, because he is known to have acted in the same say as he taught. In contrast, those whose words are not consistent with their works show that their version of justice is not right.
'''
source_url=''
source_title="EXPLANATION OF THE PSALMS 19:9"
uuid = "037218ea-9e3a-4bcb-af0f-d63da1f5795e"
