[[commentary]]
quote='''
Human weakness is not strong enough to reach the Father on its own. For when he hears, he graciously shows his indulgence, and he bestows his mercy in advance so that he is able to accept the prayers of those who implore him.
'''
source_url=''
source_title="EXPLANATION OF THE PSALMS 17:6"
uuid = "28e0c740-9c9f-4f78-a712-ae27e4d7d6d3"
