[[commentary]]
quote='''
"You who give salvation to kings, who redeemed David your servant from the sword of the wicked." He calls kings those righteous and true individuals who, as we have said, rule their bodies with the Lord"s help. The Lord gives salvation to these kings, since he has freed them from the vices of the flesh. Of them it is said in Wisdom, "He gives kings their rule." - "Explanation of the Psalms 143.10"
'''
uuid = "c2253acd-a3a1-4fb9-a24d-cce774702c1c"


[[commentary]]
quote='''
"You who give salvation to kings, who redeemed David your servant from the sword of the wicked." He calls kings those righteous and true individuals who, as we have said, rule their bodies with the Lord's help. The Lord gives salvation to these kings, since he has freed them from the vices of the flesh. Of them it is said in Wisdom, "He gives kings their rule."
'''
source_url=''
source_title="EXPLANATION OF THE PSALMS 143:10"
uuid = "8ba46c0e-93c2-41ab-9553-976079d8ecf4"
