default_year=500
wiki='https://en.wikipedia.org/wiki/Pseudo-Chrysostom'
uuid = "236d51e5-c777-4b1f-aead-bf538b50de74"
category = "Apocrypha, Documents & Liturgies"
image = "https://download.biblians.com/commentaries/fathers/Ps.-Chrysostom_Raphael_Old_Nubian.webp"
summary = "Pseudo-Chrysostom is the designation used for the anonymous authors of texts once falsely or erroneously attributed to John Chrysostom. Most such works are sermons, since more than 500 of John's actual sermons survive."
