default_year=1022
wiki='https://en.wikipedia.org/wiki/Symeon_the_New_Theologian'
uuid = "0cc51bbe-7977-45fc-ade6-58c02de770ab"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/4/41/Simeon_novyj.jpg"
summary = 'Saint Symeon the New Theologian was an Eastern Orthodox monk and poet who was one of the three saints canonized by the Eastern Orthodox Church and given the title of "Theologian". "Theologian" was not applied to Symeon in the modern academic sense of theological study; the title was intended only to recognise someone who spoke from personal experience of the vision of God. One of his principal teachings was that humans could and should experience theoria.'
