[[commentary]]
quote='''
If he is the Spirit of adoption and makes men sons of God, how can he be considered a slave, since no slave can legitimately make another free?
'''
source_url=''
source_title="POWER OF THE HOLY SPIRIT 4"
uuid = "c101bf69-3fb2-4bc0-98b2-75b168c7819a"
