default_year=1117
wiki='https://en.wikipedia.org/wiki/Anselm_of_Laon'
uuid = "07511b23-416a-47a7-be08-61ff3b4e990b"
category = "Western & Medieval Theology"
summary = "Anselm of Laon, properly Ansel, was a French theologian and founder of a school of scholars who helped to pioneer biblical hermeneutics."
