default_year=449
wiki='https://en.wikipedia.org/wiki/Eucherius_of_Lyon'
uuid = "6caa073a-5b9a-420c-bf56-c4b6f4d2ffd3"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/Statue_de_Saint_Eucherius_de_Lyon_(cropped).webp"
summary = 'Eucherius was a high-born and high-ranking ecclesiastic in the Christian church in Roman Gaul. He is remembered for his letters advocating extreme self-abnegation. From 439, he served as Archbishop of Lyon, and Henry Wace ranked him "the most distinguished occupant of that see" after Irenaeus. He is venerated as a saint within the Eastern Orthodox Church and the Roman Catholic Church.'
