[[commentary]]
quote='''
It was the incarnate Word who accomplished the mystery of our salvation. It was he who freed us and redeemed us. We believe in him who is our Savior through the cross and through his resurrection from the dead.
'''
source_url=''
source_title="AGAINST ARIUS 1A"
uuid = "276fd021-ac66-4072-bf6c-927dd74a72d6"
