[[commentary]]
quote='''
Note that Tychicus is described not as a minister to Paul but as a minister in the Lord with regard to the gospel and the mystery.
'''
source_url=''
source_title="EPISTLE TO THE EPHESIANS 2.6.21"
uuid = "2c7d63a3-5c8d-454e-9049-1c0a9806e057"
