[[commentary]]
quote='''
Does Paul mean "good works" in the future tense or those which we now perform? Taken either way they are good for us to walk in. They are witnesses to Christ's working in us.
'''
source_url=''
source_title="EPISTLE TO THE EPHESIANS 1.2.10"
uuid = "17ccce35-6fe5-44f1-99c1-64c7a9631eb0"
