[[commentary]]
quote='''
The gospel is to be carried abroad. It is to be preached among the nations. Wherever, then, it is preached, it must be heard. But so that all may hear, one must use one's feet to travel. And so do we travel with haste and urgency. .
'''
uuid = "744022f9-0ecd-41f9-8921-70eab9965982"
