[[commentary]]
quote='''
He did not make us deserving, since we did not receive these things by our own merit but by the grace and goodness of God.… But all this, as he often asserts and I insist, is in Christ. For in him is the whole mystery of the resurrection, both ours and of all others.
'''
source_url=''
source_title="EPISTLE TO THE EPHESIANS 1.2.7"
uuid = "7776af79-461f-4159-a29c-4ef38ca94b15"
