[[commentary]]
quote='''
Tychicus is sent to give the Ephesians instructions not on his own accord. Rather he was sent by Paul for this purpose. Such was Paul's concern for them and his desire that they should be well informed.
'''
source_url=''
source_title="EPISTLE TO THE EPHESIANS 2.6.22"
uuid = "149ec3c3-389e-4cd1-895c-0ae3c7abb00f"
