default_year=370
wiki='https://en.wikipedia.org/wiki/Gaius_Marius_Victorinus'
uuid = "df84f2e6-8790-4c14-9d3f-723dd32065b2"
category = "Western & Medieval Theology"
summary = """Gaius Marius Victorinus was a Roman grammarian, rhetorician and Neoplatonic philosopher. Victorinus was African by birth and experienced the height of his career during the reign of Constantius II. He is also known for translating two of Aristotle's books from ancient Greek into Latin: the Categories and On Interpretation. Victorinus had a religious conversion, from being a pagan to a Christian, "at an advanced old age", which has been described in Augustine's Confessions."""
