[[commentary]]
quote='''
This is our struggle. This is our contest, our contention and our goal. This it is that leads to the crown and the palm of victory: To do all things for him, to suffer all things for him and not to turn away. You, he says, are now "engaged in the same conflict which you saw and now hear to be mine." It is a conflict that implies chains, prison and all the deadly hazards that Paul has suffered. "So my sufferings," he says, "are confirmed in you by two things: what you hear and what you see."
'''
source_url=''
source_title="EPISTLE TO THE PHILIPPIANS 1.30"
uuid = "90a374cd-f8c8-4b06-9d46-2f09384a1d59"
