[[commentary]]
quote='''
For then, he says, the threat had vanished. But because the Gospel became sufficient, he will rescue me from all: that is to say, he will not leave me and the threat will disappear.
'''
uuid = "87c66d9c-d4b8-4fcb-ad85-e1f5ad9277b3"
