[[commentary]]
quote='''
John shows here that true knowledge means demonstrating that one is faithful to Christ by obeying his commandments.
'''
source_url=''
source_title="CATENA"
uuid = "4f712f52-3c89-4f91-9ed1-ff5117d134d7"
