[[commentary]]
quote='''
Cain became unrighteous and turned into the very first person who killed a member of his family, thereby teaching human nature the way of murder.
'''
source_url=''
source_title="CATENA"
uuid = "14ea33a3-8400-4a74-8197-6e1c8a7996b1"
