[[commentary]]
quote='''
The one who is in you is God the Father, through the Son and the Paraclete. The one in the world is Satan, for "world" here refers to evil people.
'''
source_url=''
source_title="CATENA"
uuid = "6e3e03c9-1e92-485a-aa76-71039f0cd820"
