[[commentary]]
quote='''
As always, the apostle turns to ethical matters after he has dealt with doctrine. After saying what good things are available because of Christ, he now calls us to lead the right kind of life.
'''
source_url=''
source_title="CATENA"
uuid = "1fb12b9c-62b9-405c-953a-f684479c6c24"
