[[commentary]]
quote='''
Having spoken of the greatness of the blessings of the Father's gift, the sufferings of Christ, the Holy Spirit's prediction concerning him, the prophets' proclamation, the desire of the angels—having said all this, Peter tells us to hold on to them all by faith.
'''
source_url=''
source_title="CATENA"
uuid = "5473054e-5f39-4315-9d43-c741d9833b30"
