[[commentary]]
quote='''
Why do trials produce patience? It is because patience brings those who experience it to perfection.
'''
source_url=''
source_title="CATENA"
uuid = "413453e0-320c-4898-b8cc-f2d61cf684fb"
