default_year=614
wiki='https://en.wikipedia.org/wiki/Andreas_of_Caesarea'
uuid = "07af8459-4560-4176-a7bd-bbb08b0b7239"
category = "Eastern & Byzantine Theology"
image = "https://download.biblians.com/commentaries/fathers/Andriy_Kesarijskiy.webp"
summary = "Andrew of Caesarea was a Greek theological writer and bishop of Caesarea in Cappadocia. Karl Krumbacher assigned him to the first half of the sixth century. He is variously placed by other scholars, from the fifth to the ninth century. However, today it is unquestionable that his life spanned the late sixth/early seventh centuries."
