[[commentary]]
quote='''
He will undertake to spread the mark of the beast everywhere through buying and selling, so that a violent death might come to all who do have the mark from the lack of necessities.
'''
source_url=''
source_title="COMMENTARY ON THE APOCALYPSE 13:14-17"
uuid = "8fcd9352-2f3e-4a35-b4d4-610c3302b3ab"
