default_year=1591
wiki='https://en.wikipedia.org/wiki/John_of_the_Cross'
uuid = "b512121d-4303-47df-8c4f-316fa1b89308"
category = "Reformation & Modern"
image = "https://upload.wikimedia.org/wikipedia/commons/9/9f/Zurbar%C3%A1n_%28atribuido%29-John_of_the_Cross-1656.jpg"
summary = "John of the Cross was a Spanish Catholic priest, mystic, and Carmelite friar. He is a major figure of the Counter-Reformation in Spain, and he is one of the 38 Doctors of the Church."
