default_year=534
wiki='https://en.wikipedia.org/wiki/Pseudo-Macarius'
uuid = "cd935d1e-0ace-4f23-8d9f-dd9a22a048b6"
category = "Apocrypha, Documents & Liturgies"
summary = "Pseudo-Macarius is the conventional designation of the anonymous author or authors of works falsely attributed to Macarius of Egypt."
