default_year=171
wiki='https://en.wikipedia.org/wiki/Dionysius_of_Corinth'
uuid = "72935d4d-a68a-4ff4-b94e-db7035fafb23"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/6/66/Dionysius_Of_Corinth%2C_St.png"
summary = "Dionysius of Corinth, also known as Saint Dionysius, was the bishop of Corinth circa AD 171. His feast day is commemorated on April 8."
