[[commentary]]
quote='''
Paul did not write this because of Christ's resurrection, which had already taken place, but because of ours, so that we might believe and silence our opponents.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "f999509a-dc67-4581-b240-312a58838aeb"
