[[commentary]]
quote='''
The principalities and powers will be abolished and will be left powerless.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "b7667c5f-c4f9-48f9-891b-a5c19fedaa12"
