[[commentary]]
quote='''
And he sets before them a fear by the phrase, "until I make your enemies." And so that they may not disbelieve, he assigns the submission to the Father.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title="Commentary on Acts"
uuid = "66e0db39-b9ea-47e0-bdf2-724f2eee1714"
