[[commentary]]
quote='''
A very forward and dishonest and foolish man questioned them, "not to teach, etc." The command, indeed, has already been said to be full of rashness, and it is redundant to repeat the same things to them about the same matters.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title="Commentary on Acts"
uuid = "a6e323c9-f4bf-4a6f-82c1-85a81c69f650"

[[commentary]]
quote='''
He still seemed a mere man to them. And to show that the command had been necessary, and that he spared not his own salvation, and to harden the multitude against them, they said these things.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Acts%2FTranslation-Litteral.html'
source_title="Commentary on Acts"
uuid = "3f6791bd-9825-4366-8c0a-cf2933f49175"
