[[commentary]]
quote='''
"a great priest." This, having, in common. He calls the Lord a priest.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "ad9517cd-65e4-45c9-bce6-8e96ae9406ba"

[[commentary]]
quote='''
"over the house of God." He speaks of the house of God as the faithful, according to, "I will dwell in them, and walk among them." (Lev. 26:12; 2 Cor. 6:16)
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "3baa3d6f-bb65-45ec-a16f-fdb963452c8f"
