[[commentary]]
quote='''
"who has entered."Since they were weary from evils, there was no mention made of the countless goods that were to come, he comforts them by saying that he who has entered into the third rest, which is the rest of the kingdom of heaven, rests from his works, that is, from persecutions, temptations, afflictions, just as indeed God rested from the works He had done in the first rest.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "75fd2b0f-4f54-441d-872f-86c41c6ddefc"

[[commentary]]
quote='''
In another way. "rested from his works, as God did from his own." As if, he rested. Since he has demonstrated that there is a third rest, and that some will enter into it, he comes to the conclusion and says: "From what has been said, it is certainly evident that there is another rest besides the aforementioned, and this is not for everyone, but dedicated to the people of God." Truly, the people of God are those who have believed in Him and keep His commandments.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "25a703ce-d0e5-4fcb-b65d-68824fdaa843"

[[commentary]]
quote='''
"And he himself rested." As if he had rested.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "8836336f-0084-4050-8071-7dd8a570bd4f"
