[[commentary]]
quote='''
"Above it." Of the ark.
"Cherubim of glory." Which are the glorious, or the beings of glory, namely, of God.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "029a9920-0ae1-4526-8f7a-96a10cfb6b17"

[[commentary]]
quote='''
"overshadowing the mercy seat." For above the ark, as if a square golden table, which was called the mercy seat, typifying Christ (Jn. 2:2), who is called to us the propitiation and redemption (1 Cor. 1:30). See the passage in Exodus, in the places concerning these things.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "9bde19b1-e52a-4210-8c3a-3bc9e17de80f"

[[commentary]]
quote='''
"about which we cannot now speak in detail." He wishes to show that the things seen were mysteries and types of the Truth. Therefore, it is not now, he says, to speak of them in part. For more words are needed than according to the present urge.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "a906a01e-9bc0-42e6-b495-b76ac4c63980"
