[[commentary]]
quote='''
"being designated by God a High Priest." And having been made perfect, he became the source of eternal salvation for all who obey him." Therefore, this is perfection in humans, that through sufferings they attain completeness. And He has said everything fitting for a human. "the source of eternal salvation."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "b9556bd1-3c8f-4e7e-a055-56c1ed7560ff"

[[commentary]]
quote='''
Behold also that which responds to divinity.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "5698d2ba-851a-4a26-afcc-74366adc35ec"
