[[commentary]]
quote='''
"But there is a certain one who testified somewhere, saying." Speaking to those who knew the Scriptures, Paul does not mention the names of those who say: "What is man?"
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "01f1ac73-93c9-46c2-a404-f4f170bc87fc"

[[commentary]]
quote='''
"that you are mindful of him."
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "56629b6a-e26d-4510-a1df-b2c7005228aa"

[[commentary]]
quote='''
For you have not only brought him into being, but also granted him to be well, and you will continue to be mindful, and you will visit him when he is in a bad state.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FPseudo-Oecumenian%2520Catena%2520on%2520Hebrews%2FTranslation-Litteral.html'
source_title="The Pseudo-Oecumenian Catena on Hebrews"
uuid = "2c4d2de6-9b81-412f-879f-d4364d6243b4"
