[[commentary]]
quote='''
Since all things are clearly evident and destined to occur perceptibly at that time, it is excessive to dwell on what has been acknowledged.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Oecumenius%2FCommentary%2520on%2520Revelation%2FTranslation-Litteral.html'
source_title="Commentary on Revelation"
uuid = "50eb0e8b-b8ed-43eb-bb91-aa7de00e90d5"
