[[commentary]]
quote='''
This may also be said of Christ, which is how Cyril of Alexandria interpreted it.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "2a7703ce-99d8-44f6-9fd5-9d6ca40610e4"
