[[commentary]]
quote='''
For out of his fulness do we all receive, nor does he, in giving liberally, suffer any diminution of his fulness.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cosmas%2520Indicopleustes%2FThe%2520Christian%2520Topography%2FBook%25205.html"
source_title="The Christian Topography, Book 5"
uuid = "18b26ee5-5b3b-48ab-b6df-cf4dc6870d09"
