default_year=368
wiki='https://en.wikipedia.org/wiki/Theodorus_of_Tabennese'
uuid = "4a6ad479-80c3-4413-9a50-4b336c152792"
category = "Syriac & Oriental Theology"
image = "https://download.biblians.com/commentaries/fathers/Theodore_the_Sanctified.webp"
summary = "Theodorus of Tabennese, also known as Abba Theodorus and Theodore the Sanctified, was the spiritual successor to Pachomius and played a crucial role in preventing the first Christian cenobitic monastic federation from collapsing after the death of its founder."
