[[commentary]]
quote='''
He was learned in the Scriptures, able to dispute with those who questioned him and able to demonstrate that the recent events were in agreement with the Old Testament.
'''
source_url=''
source_title="CATENA ON THE ACTS OF THE APOSTLES 18.24"
uuid = "4ed4049a-642e-4596-b008-767fdb7435a8"
