default_year=544
wiki='https://en.wikipedia.org/wiki/Arator'
uuid = "969f7590-a54b-4b2d-9d4b-1f44f64c35b3"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/Аратор_со_своей_поэмой_и_Флориан_(настоятель_монастыря_рядом_с_Миланом).webp"
summary = "Arator was a sixth-century Christian poet from Liguria in northwestern Italy. His best known work, De Actibus Apostolorum, is a verse history of the Apostles."
