[[commentary]]
quote='''
For then did the old greedy dragon taste in the head of the servant what he so thirsted after—the passion of the master.
'''
source_url=''
source_title="SERMONS 174"
uuid = "5c411d36-6a60-4b46-ab9b-e45d6c9058cb"
