[[commentary]]
quote='''
Having appeared to them while they were laboring and exhausted, He does not immediately reveal Himself, but first wishes to enter into conversation with them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520John%2FChapter%252021.html'
source_title="Commentary on John"
uuid = "e42f2d9a-184b-4365-abc3-e89eb1a9406e"
