[[commentary]]
quote='''
Death to Him! Release Barabbas to us, who had been thrown into prison as a rebel and murderer.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252023.html'
source_title="Commentary on Luke"
uuid = "72746d74-5a73-45f4-a896-0afe96d2c071"
