[[commentary]]
quote='''
You, he says, do not care for the brethren as much as God, their Creator. He appointed for them countless teachers.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Luke%2FChapter%252016.html'
source_title="Commentary on Luke"
uuid = "b0185c81-cc22-4369-a0b6-471aa10f2d21"
