[[commentary]]
quote='''
After the miracles which have been related, the Lord returns into His own country, not that He was ignorant that they would despise Him, but that they might have no reason to say, If Thou hadst come, we had believed Thee; wherefore it is said, And he went out from thence, and came into his own country.
'''
append_to_author_name=' (as quoted by Aquinas, AD 1274)'
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCatena%2520Aurea%2FCommentary%2520on%2520Mark%2FChapter%25206.html'
source_title="Catena Aurea by Aquinas"
uuid = "8ba7efea-9334-4468-b570-b92e974a8e01"

[[commentary]]
quote='''
The Lord comes to His homeland not because He did not know that they would disregard Him, but so that afterward they could not say: if He had come, we would have believed.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Theophylact%2520of%2520Ohrid%2FCommentary%2520on%2520Mark%2FChapter%25206.html'
source_title="Commentary on Mark"
uuid = "71dc2bda-3025-4a89-a074-71c7153ca2e6"
