default_year=1107
wiki='https://en.wikipedia.org/wiki/Theophylact_of_Ohrid'
uuid = "7fe5cc14-e3b3-4678-a75d-76831673faa1"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/6/61/Theophylact_the_Bulgarian.jpg"
summary = "Theophylact was a Byzantine Archbishop of Ohrid and commentator on the Bible. He is regarded as a saint in the Eastern Orthodox Church, commemorated on December 31st."
