default_year=510
wiki='https://en.wikipedia.org/wiki/Epiphanius_Scholasticus'
uuid = "e4068f06-42f8-4294-9555-420b7186659a"
category = "Western & Medieval Theology"
summary = "Epiphanius Scholasticus was a sixth-century translator of Greek works into Latin."
