[[commentary]]
quote='''
In this passage, every person should be regarded as a brother, for we are all brothers in Christ.
'''
source_url=''
source_title="SERMONS 219.2"
uuid = "25546603-52d4-4ef3-ac2b-88b41f6c8c0d"
