[[commentary]]
quote='''
The Old Testament was good, but without spiritual understanding it dies with the letter. The New Testament, through grace, restores the odor of life.
'''
source_url=''
source_title="SERMON 168.4"
uuid = "9c034900-8434-4987-9e42-d4c2a2b2c17e"
