[[commentary]]
quote='''
Although we had been dried up because of lack of the dew of God's grace, we merited to be changed into fountains and rivers. At that time Samson prayed and a fountain issued from the jawbone. This fact is clearly fulfilled in us, for the Lord himself said, "He who believes in me, from within him there shall flow rivers of living water."
'''
source_url=''
source_title="SERMON 119.4"
uuid = "1930133d-e224-498d-8b4a-62e8be5872d5"
