[[commentary]]
quote='''
Listen to the psalmist tell how anger clouds the eye of the heart: "My eyes are dimmed," he says, "with sorrow."
'''
source_url=''
source_title="SERMON 148:2"
uuid = "84e3aca3-0688-4eac-8973-2646b1f7948d"
