[[commentary]]
quote='''
The throne, the animals, the elders and the Lamb as though slain are all the church together with her head. [The church] dies for Christ that she might live with Christ. The martyrs in the church may also be understood as the Lamb slain.
'''
source_url=''
source_title="EXPOSITION OF THE APOCALYPSE 5:6, HOMILY 4"
uuid = "a2d99924-7d6d-40b3-a4cd-c73b7e8262b4"
