[[commentary]]
quote='''
The wine is to be interpreted as the blood of Christ, and the oil as the unction of chrismation.
'''
source_url=''
source_title="EXPOSITION ON THE APOCALYPSE 6:6"
uuid = "d02b0ce3-5d52-4046-b185-aa200ddc0752"
