[[commentary]]
quote='''
This signifies that the whole world, among the good and the saints, is going to find refuge in the church, so that made firm under [the church's] protection it is able to endure unto eternal life, with the help of our Lord Jesus Christ, who lives and reigns forever and ever. Amen.
'''
source_url=''
source_title="EXPOSITION ON THE APOCALYPSE 6:15, HOMILY 5"
uuid = "a9bf6922-b735-4e27-b0a9-65f9c35948f0"
