[[commentary]]
quote='''
who is worthy.... It is because Christ opened the book when he undertook the work of the Father's will, was conceived, and was born. The He broke its seals when He was slain for the human race.
'''
uuid = "bf6df8ac-2d93-4961-8620-56764c1f3336"

