[[commentary]]
quote='''
The grace of God through Jesus Christ our Lord will free you from the body of this death; it will deliver you from the law of death. But … this is going to take place at the resurrection, when you will possess a body in which no evil inclination remains.
'''
source_url=''
source_title="SERMON 177.4"
uuid = "62fd1160-5a9d-4c01-b2f2-6973501f2186"
