[[commentary]]
quote='''
It is called Solomon's portico, because Solomon went to pray there. The porches of a temple are usually named after the temple
'''
uuid = "8e31f8f6-b89d-49a1-8fdd-7b7de5c1d4a1"
