default_year=185
wiki='https://en.wikipedia.org/wiki/Theophilus_of_Antioch'
uuid = "3dcf0b19-876e-4004-857e-4ba09df5b996"
category = "Early Fathers"
image = "https://upload.wikimedia.org/wikipedia/commons/1/16/Theophilus_Antiochenus.png"
summary = "Theophilus of Antioch was Patriarch of Antioch from 169 until 183. He succeeded Eros of Antioch c. 169, and was succeeded by Maximus I c. 183, according to Henry Fynes Clinton, but these dates are only approximations. His death probably occurred between 183 and 185."
