default_year=491
wiki='https://en.wikipedia.org/wiki/Isaiah_the_Solitary'
uuid = "7ae1fe23-bba2-4055-9202-d4eb51928dc0"
category = "Eastern & Byzantine Theology"
summary = "Isaiah the Solitary, also known as Isaiah of Gaza, Isaias the Solitary, Abba Isaiah, or possibly also Isaiah of Scetis, was a Christian ascetic and monastic writer known from the Sayings of the Desert Fathers and various Palestinian Miaphysite sources. He is canonized as a saint by the Coptic Orthodox Church, with his feast day on the 11th day of the month Abib (Epip) in the Coptic calendar."
