[[commentary]]
quote='''
Just as there is one God the Father from whom are all things, so there is one Lord Jesus Christ through whom are all things.
'''
source_url=''
source_title="LETTER 50.26"
uuid = "3ea12d9e-9a46-4ae7-85a8-5a8f881fe18a"
