[[commentary]]
quote='''
The young men are a model of courage, the elders are a model of understanding, and the sons and daughters are a model of what it means to be children in Christ.
'''
source_url=''
source_title="CATENA"
uuid = "3e4729ae-093c-41d9-8044-6d9bf189ae3e"
