[[commentary]]
quote='''
Just as faith without works is dead, so the reverse is also true. Therefore let integrity in faith shine forth along with the glories of upright living.
'''
source_url=''
source_title="LETTERS 55.2"
uuid = "d10c8f91-d223-4942-92fa-ee20548f13d6"
