[[commentary]]
quote='''
He will not grant you another sign, so that he may give holy things to dogs or throw pearls before swine.…He said only the sign of Jonah will be given to them. This means the passion on the cross and the resurrection from the dead.
'''
source_url=''
source_title="COMMENTARY ON LUKE, HOMILY 82"
uuid = "17ecc84c-776e-4832-bff2-25cfcb21a8eb"
