[[commentary]]
quote='''
These words refer to Christ, who himself prophesied in the Gospels, saying: "Have you not read, 'The stone which the builders rejected, the same has become the head of the corner?' "
'''
source_url=''
source_title="CATENA"
uuid = "492a2170-304b-45f4-a35d-bc3c8bb06498"
