[[commentary]]
quote='''
"And all that dwelt at Lydda and Saron saw him, and turned to the Lord." For the man was notable.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520the%2520Acts%2520of%2520the%2520Apostles%2FHomily%252021.html'
source_title="Homily on Acts 21"
uuid = "c09c0cd3-bbd0-4698-8958-e51b7a6f70de"

[[commentary]]
quote='''
"And having seen him," it says, "all that dwelt in Lydda, and Saron, turned unto the Lord." Observe everywhere the signs taking place. But let us so believe them, as if we were now beholding them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520the%2520Acts%2520of%2520the%2520Apostles%2FHomily%252021.html'
source_title="Homily on Acts 21"
uuid = "39108187-b22d-424e-bceb-77fb0ee81d17"
