[[commentary]]
quote='''
Quite understandably, given what things he had seen. He is the first and only one to see the Father and the Son as in a vision.… When the advent of our Lord was soon drawing near, quite appropriately marvelous visions also appeared.
'''
source_url=''
source_title="COMMENTARY ON DANIEL 7:7"
uuid = "eb9a2842-2be0-40bf-a149-dd5da4b4bf37"
