[[commentary]]
quote='''
He means the events in the time of the Maccabees: Judas, Simon and John.
'''
source_url=''
source_title="DISCOURSES AGAINST JUDAIZING CHRISTIANS 5:7.5"
uuid = "4eadd688-4760-4367-ad56-2fae991473a6"
