[[commentary]]
quote='''
Which he proves by ancient testimony thus:
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520Galatians.html'
source_title="Homily on Galatians 3"
uuid = "19abe88d-9fae-4a1c-93ce-060dba143f30"
