[[commentary]]
quote='''
"And ye have forgotten the exhortation." That is, And ye have slackened your hands, ye have become faint.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520Hebrews%2FHomily%252029.html'
source_title="Homily on Hebrews 29"
uuid = "fc8ed498-3a93-4f44-a2e6-e1f6a3b6bbf6"

[[commentary]]
quote='''
"Which" (he says) "speaketh unto you as unto sons, My son, despise not thou the chastening of the Lord, nor faint when thou art rebuked of Him." He has drawn his encouragement from the facts themselves; over and above he adds also that which is drawn from arguments, from this testimony.

"Faint not" (he says) "when thou art rebuked of Him." It follows that these things are of God. For this too is no small matter of consolation, when we learn that it is God's work that such things have power, He allowing them; even as also Paul says; "He said unto me, My grace is sufficient for thee: for My strength is made perfect in weakness." He it is who allows them.
'''
source_url='https://historicalchristian.faith/by_father.php?file=John%2520Chrysostom%2FHomilies%2FOn%2520Hebrews%2FHomily%252029.html'
source_title="Homily on Hebrews 29"
uuid = "3e14ed30-851a-4f7d-ae44-9550c7354dcf"
