[[commentary]]
quote='''
"Or like a stillborn child that never sees the light," he says. Notice how, in order that he may not appear to be arrogant, he even compares himself with a stillborn child, so absolutely wretched and pitiful is he.
'''
source_url=''
source_title="COMMENTARY ON JOB 3:20-23"
uuid = "1a63db7f-cca2-43cf-9b68-14966a24daa2"
