[[commentary]]
quote='''
The scribes asserted that only God could forgive sins, yet Jesus not only forgave sins, but showed that he had also another power that belongs to God alone: the power to disclose the secrets of the heart. 
'''
source_url=''
source_title="THE GOSPEL OF ST. MATTHEW, HOMILY 29.1"
uuid = "e5d467ae-e4d1-4c0c-b79b-fabbfa363321"
