default_year=407
wiki='https://en.wikipedia.org/wiki/John_Chrysostom'
uuid = "31c70076-2b97-4b1a-9f8f-2139ca23cafc"
category = "Eastern & Byzantine Theology"
image = "https://download.biblians.com/commentaries/fathers/Johnchrysostom.webp"
summary = "John Chrysostom was a Church Father who served as Archbishop of Constantinople. He is known for his preaching and public speaking, his Divine Liturgy of Saint John Chrysostom, and his ascetic sensibilities."
