default_year=1791
wiki='https://en.wikipedia.org/wiki/John_Wesley'
uuid = "85682e86-7daf-4888-8b41-d3c5313f1f9a"
category = "Reformation & Modern"
image = "https://download.biblians.com/commentaries/fathers/John_Wesley_by_George_Romney.webp"
summary = "John Wesley was an English cleric, theologian, and evangelist who was a principal leader of a revival movement within the Church of England known as Methodism. The societies he founded became the dominant form of the ongoing independent Methodist movement."
