[[commentary]]
quote='''
His intent was to divide the money and with one portion to purchase praise and the impression of piety, but to save the other portion for himself in case some need should arise.
'''
uuid = "efe37529-f16d-4d91-a3db-1ad0bc88deff"
