[[commentary]]
quote='''
And leaping and praising God:
To conceal the kind deeds of God is a matter of ingratitude; to attribute them to human endeavor is impiety.
'''
uuid = "b19c29ce-0989-49dc-be31-b26fedb32f5e"
