default_year=544
wiki='https://en.wikipedia.org/wiki/Facundus_of_Hermiane'
uuid = "74f903ea-121b-432c-b9e3-992ac359998f"
category = "Western & Medieval Theology"
summary = "Facundus of Hermiana was a 6th-century Christian author, and bishop of Hermiana in North Africa."
