default_year=465
wiki='https://en.wikipedia.org/wiki/Maximus_of_Turin'
uuid = "1d26f8f1-6b23-4b0b-8bc1-9a872bd9c663"
category = "Western & Medieval Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/2/23/Maximus_Taurinensis.JPG"
summary = 'Maximus of Turin was a Roman Christian prelate known as the first Bishop of Turin. He was a theological writer who "made a great contribution to the spread and consolidation of Christianity in Northern Italy".'
