default_year=1637
wiki='https://en.wikipedia.org/wiki/Cornelius_a_Lapide'
uuid = "7b3ae451-8a6f-4a3d-a398-fec0446a83cc"
category = "Reformation & Modern"
image = "https://upload.wikimedia.org/wikipedia/commons/3/37/Cornelius_a_Lapide%2C_8B6292100_%28cropped%29.jpg"
summary = "Cornelius Cornelii a Lapide, SJ was a Flemish Jesuit priest and noted exegete of Sacred Scripture."
