default_year=490
wiki='https://en.wikipedia.org/wiki/Faustus_of_Riez'
uuid = "6de61a5c-3921-4f77-93c8-a25049a1d7a3"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/Riez_Notre-Dame_de_l'Assomption_Vitrail_Saint_Fauste.webp"
summary = "Faustus of Riez was an early Bishop of Riez (Rhegium) in Southern Gaul (Provence), the best known and most distinguished opponent of Pelagianism."
