default_year=410
wiki='https://en.wikipedia.org/wiki/Gaudentius_of_Brescia'
uuid = "5a003d3b-88e9-4520-a11a-e64b0177c0d1"
category = "Western & Medieval Theology"
summary = "Gaudentius was Bishop of Brescia from 387 until 410, and was a theologian and author of many letters and sermons. He was the successor of Philastrius."
