[[commentary]]
quote='''
Now, in as much as a sinner receives our Lord's body and blood in faith, he is in our Lord, and our Lord is in him, as our Lord himself says. Where the Lord dwells, there is his Spirit too.
'''
source_url=''
source_title="ON THE INDWELLING OF THE HOLY SPIRIT"
uuid = "ed6527d9-d481-49b5-942f-59654411db51"
