default_year=150
wiki='https://en.wikipedia.org/wiki/Epistle_to_Diognetus'
uuid = "88a08f5d-f93a-44ea-aa09-89fff8043d54"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/4/49/Codex_Tchacos_p33.jpg"
summary = "The Epistle to Diognetus is an example of Christian apologetics, writings defending Christianity against the charges of its critics. The Greek writer and recipient are not otherwise known. Estimates of dating based on the language and other textual evidence have ranged from AD 130, to the general era of Melito of Sardis, Athenagoras of Athens, and Tatian."
