[[commentary]]
quote='''
The Jews were putting Christ to the test, because it was he who spoke to Moses. Paul is warning us here not to do the same as they did.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "2285e728-fea8-4adf-8735-1e3f2f34c59a"
