[[commentary]]
quote='''
Paul repeats what he said above in order to underline its importance.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "1142cd36-ec10-4ea7-adaf-71e50348d948"
