[[commentary]]
quote='''
Because the Corinthians did not love one another, Paul gives them this teaching from himself, in order that they might learn to love each other with the same love with which they were loved by the apostle, not with carnal emotion but in Christ Jesus.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "3afebd74-a0b6-4e82-b62b-12a91d0bd520"
