[[commentary]]
quote='''
Paul is telling the Corinthians that nobody else will ever love them the way he does.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "1bcb1774-664a-40e1-b755-0c024e73d2d5"
