[[commentary]]
quote='''
This means that a weak brother cannot say that he is not a part of the body simply because he is not strong.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "18dfaf29-ace8-4b8c-9a6c-00419d0a41f5"
