[[commentary]]
quote='''
The Corinthians were wrong in two ways. First, they were unfaithful, and second, they were expounding God's laws with a show of respect but in reality attributing their authority to idols.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "69865cc0-cc80-4e02-a29c-d4487927ccc0"
