[[commentary]]
quote='''
Those who love Christ are fools as far as the world is concerned.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "c3e12126-ccba-4979-a4d0-4cc08e79ece3"
