[[commentary]]
quote='''
This is what Paul meant when he said that all things were lawful to him.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "d80d55d7-65d3-4b83-8fb5-92fdf6d5491b"
