[[commentary]]
quote='''
A bishop cannot do anything about unbelievers. But a brother who is caught doing such things he can bar not only from the sacraments but also from common intercourse with his fellows, so that when he is avoided he may feel ashamed and repent.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "ceef2574-b2ff-4c28-a3a1-9de7c25b3881"
