[[commentary]]
quote='''
To eat and drink to God's glory is to eat and drink after giving thanks to the Creator.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "ba1865df-e5e9-4b2f-a797-b608c15e222f"
