[[commentary]]
quote='''
The graces of the Lord which are seen in persons do not relate to the merit of the individual but to the honoring of God.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "98874885-e7bc-4224-b8d8-c54ab3211158"
