[[commentary]]
quote='''
Paul's intention is to avoid fornication, not to put hindrances in the way of those seeking a higher way of life.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "035a103b-77d9-4bb1-b1d8-37055d463250"
