[[commentary]]
quote='''
Paul does not exercise his rights because they might be an obstacle to the gospel. That left him free to argue that he was not one of the false apostles.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "9e660d59-9f9f-43c0-ba34-2d147847e34d"
