[[commentary]]
quote='''
The Spirit of God is shared between God and human beings when we are united to the Lord.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "5b5cc669-74c3-4e3d-8396-9e73f990d1fe"
