[[commentary]]
quote='''
Paul says this because the person who involves himself in contamination is united with the person with whom he involves himself. Sexual immorality makes them both one, in nature as well as in sin. Commentary on Paul's Epistles.
'''
uuid = "f1c157a0-b006-4d07-a36e-c24f5a6b67cb"
