[[commentary]]
quote='''
It is all right to have a wife, but if she commits adultery she is to be rejected. Likewise, it is all right to eat meat, but if it has been sacrificed to idols it is to be refused.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "7f9f0f27-c2b0-4d49-b059-38bf5fc6c4b6"
