[[commentary]]
quote='''
Paul is acting here like a good physician who alleviates the pain caused by his operation to remove the disease, so that the sick person will let himself be cured.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "898f60a5-c4f7-4ec8-aba5-21ccccbcae36"
