[[commentary]]
quote='''
The salvation that comes to women through childbearing applies only to the children who are reborn in Christ.
'''
source_url=''
source_title="COMMENTARY ON THE FIRST LETTER TO TIMOTHY"
uuid = "f1147a64-c25c-43cc-b0fb-a9f5a52bf423"
