[[commentary]]
quote='''
Paul wanted the Corinthians to understand that his love for them was beneficial, not harmful.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "84ade9a2-b5c6-483d-943a-3caff3dcfe43"
