[[commentary]]
quote='''
Paul accepted contributions from the Macedonians because they corrected their faults. But he refused anything from the Corinthians because they were less ready to correct theirs.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "790339ce-2308-4075-962a-dce3ab3fa573"
