[[commentary]]
quote='''
By this service Paul and his companions are testing the Corinthians' attitude and magnifying the Lord.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "37103447-b918-43a4-9fbe-08fca0d16e89"
