[[commentary]]
quote='''
It is obvious that if Paul arrives and finds that the Corinthians are not what they have been expected to be, he will be chagrined and they will feel even more frustrated.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "98f8d637-60b3-4a56-8a13-41a431bc8284"
