[[commentary]]
quote='''
Paul is saying that Christ confirms the Gentiles in the faith promised to the Jews, because he has made us both one.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "d3cce19f-1672-47af-a94c-b6b77417defe"
