[[commentary]]
quote='''
Paul is saying that our present afflictions are light because they are happening within time and space. In return for this light tribulation, we shall gain a degree of glory beyond measure. Commentary on Paul's Epistles.
'''
uuid = "b52b7652-0bc6-4425-b4e0-8c9db75ab602"
