[[commentary]]
quote='''
Paul is saying that people who long for heavenly things despise the things of this world, because in comparison with what they want, these things are nothing.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "7baa61e5-5d87-4c32-b9a3-4e0120026220"
