[[commentary]]
quote='''
What Paul says is backed up by his actions. It is through actions that we learn what a person really thinks.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "f46d8345-fe39-42ec-a835-f45a8b7bf009"
