[[commentary]]
quote='''
Paul is referring here to those who did not accept that his teaching was spiritual.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "87eb08fe-954f-4dd3-968e-0aab2df465da"
