[[commentary]]
quote='''
Some of Paul's sleepless nights were voluntary, but others were forced on him. When he was in dire straits, he had to stay awake and seek God's help. Furthermore he taught not only in the daytime but at night as well. He was cold and exposed when he was shipwrecked on the island of Malta, where the local people came to his rescue..
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "196229fb-2c35-4448-8032-e0b4b4b93b0b"
