[[commentary]]
quote='''
Paul takes an intellect captive when he conquers it just as it is contradicting him by its reasonings, and he leads it, humbled and tame, to the Christian faith.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "f8f3ae55-74ed-4ad3-803f-94f80a2496a6"
