[[commentary]]
quote='''
From the abundance of his holiness and goodness it is possible to know what works delight God. … In his holiness we are purified. In his mercy we are brought to full and perfect righteousness.
'''
source_url=''
source_title="EPISTLE TO THE EPHESIANS 5.10"
uuid = "8268e929-ce18-47b9-afbb-28e3310208b0"
