[[commentary]]
quote='''
The hope of their faith lies in a heavenly reward. When they truly know what the fruit of believing is, they will become more eager in acts of worship.
'''
source_url=''
source_title="EPISTLE TO THE EPHESIANS 1.18.1"
uuid = "22d0af33-9e0e-4a05-a004-af60ff07ff97"
