default_year=384
wiki='https://en.wikipedia.org/wiki/Ambrosiaster'
uuid = "831d119a-d399-4e4e-996b-99cecb2af0e7"
category = "Apocrypha, Documents & Liturgies"
summary = """Ambrosiaster or Pseudo-Ambrose is the name given to the unknown author of a commentary on the epistles of Saint Paul, written some time between 366 and 384 AD. The name "Ambrosiaster" in Latin means "would-be Ambrose". Various conjectures have been made as to Ambrosiaster's true identity, and several other works have been attributed to the same author, with varying degrees of certainty."""
