[[commentary]]
quote='''
His imprisonment for Christ's sake is becoming known. This is his distinctive honor. Now others who love him may rejoice with him.
'''
source_url=''
source_title="EPISTLE TO THE PHILIPPIANS 1.17.1"
uuid = "b09e67c6-70ce-4394-9ed5-6c5dd68e1c72"


[[commentary]]
quote='''
Who are "all the rest"? The whole of Jewry, in addition to all the churches of the Gentiles. The former still has precedence, since to them the promise was first made.
'''
source_url=''
source_title="EPISTLE TO THE PHILIPPIANS 1.17.1"
uuid = "ab10f5a7-1539-4cb1-816a-4470c41ed09f"
