[[commentary]]
quote='''
It is clear that Paul says he is happy because Philemon was providing for the needs of the saints. For this is certain that Philemon will obey his requests since it is clear that he is of higher rank.
'''
uuid = "566396a7-467c-4b0a-8e1d-177f7b85ef16"
