[[commentary]]
quote='''
The greeting of the brothers is an act of mutual consolation. It calls to mind those who have been split apart.
'''
source_url=''
source_title="EPISTLE TO THE PHILIPPIANS 4.22"
uuid = "651ce947-2f19-49e3-a0b0-f85158b69fb4"
