[[commentary]]
quote='''
These are understood to have been of one mind because it was for that reason that Paul greeted them together.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "a6528937-451b-4da3-a2fc-a7243778eab1"
