[[commentary]]
quote='''
Here Paul teaches us that we ought to know that the bounds of righteousness must not be transgressed, so that not only will it be of service to us but it will not harm anyone else either.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "226da7ad-d3b4-4e2c-8d6a-f3a494801964"
