[[commentary]]
quote='''
This is what it means to love Christ, that we should encourage one another to live in a way which corresponds to the way in which the body is made perfect in Christ.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "7dfdb386-57c0-4547-95b3-0149a4151313"
