[[commentary]]
quote='''
Paul does not greet Apelles as a friend or fellow worker, but because he has been tried in temptations and found to be faithful to Christ. Aristobulus is to be understood as having assembled the brethren in Christ. Paul approves of this so much that he regards those whom he has gathered together to be worthy of greeting as well.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "5ed66e4c-da30-4cf3-bcb1-d54c69dc83ef"
