[[commentary]]
quote='''
Paul says this because the righteousness of the law of Moses did not make people guilty as long as they kept it.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "dba9744c-d16e-4741-8fec-e6e81bcde9a6"
