[[commentary]]
quote='''
Paul asks for their prayers … not because he deserves them but because he is following the principle that the church ought to pray for its pastor. For when many ordinary people come together and agree they become great, and the prayers of many cannot be ignored. Therefore, if the Romans want to see the apostle, let them pray earnestly that he may be set free so that they may receive him in the joy of brotherly love.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "8fc4bdca-4658-4d13-a98b-46645c9f06f5"
