[[commentary]]
quote='''
Paul wants the Romans to understand that they ought to be concerned with this sort of thing, for those who live because of mercy and who are justified before God ought to show their devotion to their brothers.
'''
source_url=''
source_title="COMMENTARY ON PAUL'S EPISTLES"
uuid = "52c6c5f0-5e65-4053-a5a9-848e7a6d8ee4"
