[[commentary]]
quote='''
Whoever loves Christ must demonstrate this in the way he treats his slaves, knowing that the Lord will require of him whatever he expects from them.
'''
uuid = "d08cea58-63ff-42a1-9341-a1c6f85dda9b"
