[[commentary]]
quote='''
The Lord is wise, so by rejoicing in the Lord, the righteous rejoice in wisdom.
'''
source_url=''
source_title="NOTES ON THE PSALMS 32[33].1"
uuid = "d4d2f907-a008-4f96-be68-25f02b98ebbf"
