[[commentary]]
quote='''
The reasons of temptation, when they are realized, provide a broad plane for the soul.
'''
source_url=''
source_title="NOTES ON THE PSALMS 30[31].9"
uuid = "cc3abed9-4a7e-41ee-a955-e3e5fd69326f"
