[[commentary]]
quote='''
One who speaks falsely receives mercy when he becomes silent. He gives up deceit.
'''
source_url=''
source_title="NOTES ON THE PSALMS 30[31].19"
uuid = "db64c4f7-42fa-43c5-b6ec-701d1ae4ddbc"
