[[commentary]]
quote='''
Nothing nourishes like that which nourishes the spirit. Blessed are those who weep, for they will laugh.
'''
source_url=''
source_title="NOTES ON THE PSALMS"
uuid = "7f504371-05c5-4fd9-97f5-bb51830b4dff"


[[commentary]]
quote='''
Seeing that God is Creator, he is in everything made; seeing that he is excellence and wisdom, he is in all holy powers.… God is even in people sometimes in excellence, sometimes in accomplishment: it is of angels to behave always according to God; of demons, never; of people to behave sometimes rightly, sometimes not.
'''
source_url=''
source_title="NOTES ON THE PSALMS 41[42].4"
uuid = "279909ee-f477-4289-a1f4-2ffb3c8c42ed"
