[[commentary]]
quote='''
When Moses delivered the people from Egypt, all those who did not believe perished.
'''
source_url=''
source_title="COMMENTARY ON JUDE"
uuid = "7bbcd185-13e4-4613-a4a4-7dbfe4938e5b"
