[[commentary]]
quote='''
The word sin does not refer to a particular substance but to the manner and life of one who has sinned.… Paul calls nothing sin except the one who is the source and begetter of sin, viz., the devil.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "56eae9e9-8ec1-4245-9271-fc4a3c9387ab"
