[[commentary]]
quote='''
For us the end for which we do all things and toward which we hasten is the blessed life in the world to come.
'''
source_url=''
source_title="HOMILY 19 ON PSALM 48"
uuid = "ee2b3fd9-85b9-4cb4-a5be-6eb723f1f66e"
