[[commentary]]
quote='''
If God is love, as John says, then it must be that the devil is hatred. As he who has love has God, so he who has hatred has the devil dwelling in him.
'''
source_url=''
source_title="ASCETICAL DISCOURSES 2"
uuid = "45dd336e-975a-4293-912b-cf5513bafed2"
