[[commentary]]
quote='''
What is meant by "a heaven of brass"? Absolute dryness and lack of aerial waters through which the earth produces its fruits.
'''
source_url=''
source_title="EXEGETIC HOMILIES 3.8"
uuid = "167980b2-1d8a-4ea1-80b5-eea49ebb50ab"
