[[commentary]]
quote='''
We believe that the Spirit is present everywhere, while the rest of the bodiless powers are circumscribed by place.
'''
source_url=''
source_title="ON THE HOLY SPIRIT 23:54"
uuid = "41baf2d8-6cdf-4e10-93a4-24d81de4ef06"
