[[commentary]]
quote='''
Anger causes tongues to become unbridled and speech unguarded. Physical violence, acts of contempt, reviling, accusations, blows and other bad effects too numerous to recount are born of anger and indignation.
'''
source_url=''
source_title="SERMONS 10"
uuid = "ac7f165f-df2c-454b-b0c1-2ad4c6319c1f"
