[[commentary]]
quote='''
We drag our body like a shadow along the ground, but we guard our soul as one that shares in the citizenship of heaven.
'''
source_url=''
source_title="ON BAPTISM 1.21"
uuid = "2b177c0f-aa6e-4e5a-9cb0-ce59846d186f"
