[[commentary]]
quote='''
Second, of the Egyptians: when it shall be heard in Egypt: behold I do a thing in Israel: and whosoever shall hear it, both his ears shall tingle (1 Sam 3:11).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Isaiah.html'
source_title="Commentary on Isaiah"
uuid = "f3555593-96d2-4b57-ae2e-c74dd4ae5f63"
