[[commentary]]
quote='''
God is said 'to change His mind,' metaphorically, inasmuch as He bears Himself after the manner of one who repents, by 'changing His sentence, although He does not change His plan.
'''
uuid = "be653e3d-4259-46f4-a8ba-173fc8f964f5"
