[[commentary]]
quote='''
He concludes: Thus you will know them by their fruits.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Matthew.htm'
source_title="Commentary on Matthew"
uuid = "98464098-fd0c-4a19-af25-ae3d58b6d9bf"
