[[commentary]]
quote='''
I brought him to your disciples, and they could not cure him. Here the malice of this man is touched upon, because he wished to accuse the disciples; hence Sirach 11:33: he who sets a stain on the elect.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Thomas%2520Aquinas%2FCommentary%2520on%2520Matthew.htm'
source_title="Commentary on Matthew"
uuid = "faf2fe46-6ed2-4a85-b557-8c102dd9fe5b"
