default_year=1274
wiki='https://en.wikipedia.org/wiki/Thomas_Aquinas'
uuid = "16077daf-6b57-4ccc-929a-15e00fe89078"
category = "Western & Medieval Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/St-thomas-aquinasFXD.jpg/3840px-St-thomas-aquinasFXD.jpg"
summary = "Thomas Aquinas was an Italian Dominican friar and priest, theologian, and philosopher. He is considered one of the most influential thinkers in the history of Catholic theology and Western philosophy."
