default_year=446
wiki='https://en.wikipedia.org/wiki/Proclus_of_Constantinople'
uuid = "61f55908-d00b-4219-b1ec-546f5ffa758e"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/c/ca/Proclus_of_Constantinople_%28Menologion_of_Basil_II%29.jpg"
summary = "Proclus of Constantinople was the Archbishop of Constantinople from 434 until his death. Renowned for his homiletic abilities, Proclus played a central role in the Nestorian controversy. His contributions to the theology of the developing cult of the Virgin Mary place him among the early and foremost Marian theologians. He is venerated as a saint in the Catholic Church, the Eastern Catholic Churches, the Eastern Orthodox Church, and Oriental Orthodoxy."
