[[commentary]]
quote='''
The great sun, when compared with the Sun of righteousness, is vanity.
'''
source_url=''
source_title="COMMENTARY ON ECCLESIASTES 1:5"
uuid = "72c84486-e167-43da-b904-21c9b600c9d2"
