default_year=217
wiki='https://en.wikipedia.org/wiki/Pope_Zephyrinus'
uuid = "81f52d46-3ba5-485b-aebb-59007930e693"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/2/21/Fresco_of_Pope_Zephyrinus_-_Basilica_of_Saint_Paul_Outside_the_Walls_%28Before_1823%29.png"
summary = "Pope Zephyrinus was the bishop of Rome from the year 199 until his death on 20 December 217. He was born in Rome, and succeeded Victor I. Upon his death on 20 December 217, he was succeeded by his principal advisor, Callixtus I. He is known for combating heresies and defending the divinity of Christ."
