default_year=200
wiki='https://en.wikipedia.org/wiki/Acts_of_Peter'
uuid = "ef06d9c2-438b-4370-9c7e-3ce003f3523e"
category = "Apocrypha, Documents & Liturgies"
image = "https://upload.wikimedia.org/wikipedia/commons/4/49/Codex_Tchacos_p33.jpg"
summary = "The Acts of Peter is one of the earliest of the apocryphal Acts of the Apostles in Christianity, dating to the late 2nd century AD. The majority of the text has survived only in the Latin translation of the Codex Vercellensis, under the title Actus Petri cum Simone. It is notable for a description of a miracle contest between Saint Peter and Simon Magus, the first record of the tradition that Saint Peter was crucified head-down, and as the origin of the saying Quo vadis?"
