default_year=450
wiki='https://en.wikipedia.org/wiki/Sozomen'
uuid = "d9191aab-29e4-4261-bc92-cc330f0ba637"
category = "Eastern & Byzantine Theology"
summary = "Salamanes Hermias Sozomenos, also known as Sozomen, was a Byzantine Empire era lawyer and historian of the Christian Church of Palestinian origin."
