[[commentary]]
quote='''
And in knowledge, temperance. So that when they have learned to do well, immediately they abstain from evils, lest knowledge of heavenly things fall in vain, if one neglects to restrain himself from earthly temptations.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520the%2520Catholic%2520Epistles.html"
source_title="Commentary on the Catholic Epistles"
uuid = "37fd87e3-3289-4de8-aaa1-885dfda0a585"


[[commentary]]
quote='''
And in temperance, patience. It is always necessary that temperance is accompanied by patience, so that whoever has learned to restrain himself from the pleasures of the world may also endure adversities with a firm heart, armed for justice from the right hand and the left (2 Corinthians 6).
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520the%2520Catholic%2520Epistles.html"
source_title="Commentary on the Catholic Epistles"
uuid = "c9b021b7-4497-4654-9358-1a82355b784a"


[[commentary]]
quote='''
And in patience, godliness. So that he may be kind towards those whom he patiently endures, according to that of the apostle Paul: "Charity is patient, is kind" (1 Corinthians 13).
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520the%2520Catholic%2520Epistles.html"
source_title="Commentary on the Catholic Epistles"
uuid = "a9fedaa7-f4a3-446a-9303-0a0df01a71c8"
