[[commentary]]
quote='''
But the crowds paid attention to what was being said by Philip. From this chapter and from the story of the Samaritan woman, it is proven that this nation was prompt in spirit to believe.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Acts.html"
source_title="Commentary on Acts"
uuid = "8b081b1e-796f-4c65-8f72-9d64bd4bb39d"
