[[commentary]]
quote='''
Bringing bulls and garlands before the gates. The bulls for sacrifice, and the garlands, either to decorate the face of the temple according to the custom of the Gentiles or to place them upon those they would sacrifice to as gods.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Acts.html"
source_title="Commentary on Acts"
uuid = "1691e1e4-2ad5-44a1-b7d1-4f81bd9b2253"


[[commentary]]
quote='''
The priest of Jupiter, who was in front of the city, bringing bulls and garlands before the gates, etc. It was the custom of the gentiles, according to Pliny, that when sacrificing to the honor of their gods, they would place garlands on both the victims and themselves.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FRetractions%2520on%2520Acts.html"
source_title="Retractions on Acts"
uuid = "52897411-b364-4d79-ac85-965dfd51c2a3"
