[[commentary]]
quote='''
The Spirit said to him: Behold, three men seek you. He heard this in his mind from the Spirit, not in the ear of the flesh.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Acts.html"
source_title="Commentary on Acts"
uuid = "62b588cf-1d7c-44ca-8ed9-b6d7d8361f10"
