[[commentary]]
quote='''
Indeed, Sarug lived thirty years and begot Nachor. The seventy interpreters have it one hundred and thirty.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Genesis.html"
source_title="Commentary on Genesis (Hexaemeron)"
uuid = "9f5d30b7-0a4d-4e5a-a7ed-e8985412dc26"
