[[commentary]]
quote='''
But Heber lived thirty-four years and begot Phaleg. The seventy interpreters have it one hundred and thirty-four.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Genesis.html"
source_title="Commentary on Genesis (Hexaemeron)"
uuid = "fbda8dc7-ca67-41f2-afef-a66a38ce9ff7"


[[commentary]]
quote='''
Indeed, Phaleg lived thirty years and begot Reu. The seventy interpreters have it one hundred and thirty.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Genesis.html"
source_title="Commentary on Genesis (Hexaemeron)"
uuid = "12b4ae52-1262-40c8-91e7-796fe5a06496"
