[[commentary]]
quote='''
Loud and wayward, etc. Desiring to disturb the peace of the Church.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Proverbs.html"
source_title="Commentary on Proverbs"
uuid = "09bfd66b-56ff-4e5c-8c34-ab871d55709c"


[[commentary]]
quote='''
Unable to remain at home with her feet. There is no heresy content with its first disciples: for they are its house, but it always seeks new ones to deceive.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Proverbs.html"
source_title="Commentary on Proverbs"
uuid = "86cd1386-ea8e-4d9f-a7f4-6b2f3ee2a8e1"
