[[commentary]]
quote='''
To call passersby who walk by the way, etc. Heresy often calls the Catholics to deception, seeing them proceed on the right path, wishing to quickly pass through this world and hasten to the eternal homeland.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Proverbs.html"
source_title="Commentary on Proverbs"
uuid = "d20343f0-20e3-4c1a-8a38-39f668b0876a"
