[[commentary]]
quote='''
There is no wisdom, no prudence, etc. Whatever the heretics counsel and think is nothing, and vain and useless.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Proverbs.html"
source_title="Commentary on Proverbs"
uuid = "5b3248fb-e461-4dd9-b052-87051d2ebd98"
