[[commentary]]
quote='''
What, my beloved; what, beloved of my womb? You understand, "What shall I say to you, my son, who was born from my womb, chosen for the kingdom?"
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Proverbs.html"
source_title="Commentary on Proverbs"
uuid = "7c9fc33f-c760-425a-9a45-61406ee16151"


[[commentary]]
quote='''
What, beloved of my vows? That is, who was chosen in this that I desired with all devotion.
'''
source_url = "https://historicalchristian.faith/by_father.php?file=Bede%2FCommentary%2520on%2520Proverbs.html"
source_title="Commentary on Proverbs"
uuid = "bb906c42-b44c-4641-92ba-38cf25b30e53"
