[[commentary]]
quote='''
Through the grace of baptism men can by receiving the Holy Spirit be changed from sons of the devil into sons of God.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Bede%2FHomilies%2520on%2520the%2520Gospels.html'
source_title="Homilies on the Gospels 1.12"
uuid = "18d619e8-020c-4aa2-bf2a-ef81eef45698"
