default_year=420
wiki='https://en.wikipedia.org/wiki/Palladius_of_Galatia'
uuid = "a58c5796-7480-4a7e-8937-7ef23452fe57"
category = "Eastern & Byzantine Theology"
summary = "Palladius of Galatia was a Christian chronicler and the bishop of Helenopolis in Bithynia. He was a devoted disciple of Saint John Chrysostom. He is best remembered for his work, the Lausiac History. He was also the author of the Dialogue on the Life of Chrysostom."
