[[commentary]]
quote='''
I shall console myself and … not allow myself to be alarmed by my thoughts but to hope in you, my God, to whom I should also give thanks, for from you it is also possible to hope for salvation.
'''
source_url=''
source_title="COMMENTARY ON PSALM 43"
uuid = "3d36ec33-7c89-47a7-b762-db5f1a94a4cf"
