[[commentary]]
quote='''
"Knows" means makes his own, as in the first psalm, "Because the Lord knows the ways of the righteous," that is, makes them his own.
'''
source_url=''
source_title="COMMENTARY ON PSALM 37"
uuid = "9aea20fe-3522-40d3-ac14-d8b706ea27de"
