[[commentary]]
quote='''
What is it that I am asking? For you not to keep silent if ever I sin as a human being or dismiss without concern my situation, leaving me unschooled in better ways. Instead, correct and reform me in a loving way.… Do not put me beyond your care.
'''
source_url=''
source_title="COMMENTARY ON PSALM 27"
uuid = "25c13d92-f9a9-4f27-9fd6-e9d9d1bcf5b8"
