[[commentary]]
quote='''
Even if the godless and demons and agitators surround us, even if they besiege us and cut us off, you will render us superior with your help.
'''
source_url=''
source_title="COMMENTARY ON PSALM 12"
uuid = "bcd69593-53c2-4400-9ba8-f6bf43e11fe5"
