[[commentary]]
quote='''
Just as I sinned and was punished, so I acknowledged it and was saved.… He wishes to bring out also the promptness of God's lovingkindness, saying, I shall confess, that is, I resolved to confess the fault to the Lord, and your pardon anticipated my confession.
'''
source_url=''
source_title="COMMENTARY ON PSALM 32"
uuid = "55c7ae86-0ea7-4c70-9919-7450beaef198"
