[[commentary]]
quote='''
When their sins are taken away and forgiven their salvation will be clear and indisputable.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "08c39124-229d-4526-9611-3f33d7f97cdd"
