[[commentary]]
quote='''
The spirit of stupor prevented them from making the hard choice of repentance and conversion.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "8abce2ca-aeed-4073-ba41-cc41bb3f71a7"
