[[commentary]]
quote='''
Paul says that he wants Christians to have the right spirit, even if others think differently.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "703d5a23-c90f-44cc-8bda-b38c5715b86e"
