[[commentary]]
quote='''
By "the God of all hope" Paul means that God has blessed us with the hope of things to come.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "1d916b6f-6c85-4781-9857-b6dd546e3fb7"
