[[commentary]]
quote='''
The apostle has expressed himself in this way … because he wants to show that the law and grace are completely incompatible and that the two of them can never go together. Of necessity, one must drive the other out.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "793657c3-141d-48e6-bbea-3151591cc459"
