[[commentary]]
quote='''
Look how great Christ's grace is in that he has set us free from condemnation.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "98b77a99-be3c-467e-b473-2ba148838c0f"
