[[commentary]]
quote='''
I think Isaiah loves to call the activities of the Spirit "spirits."
'''
source_url=''
source_title="ON PENTECOST, ORATION 41:3"
uuid = "f448be3b-0bf4-46e2-b449-1ca06debe53c"
