[[commentary]]
quote='''
Isaiah calls to you to know your owner, like the ox, and to know the manger of your Lord, like the donkey.
'''
source_url=''
source_title="ON THE BIRTH OF CHRIST, ORATION 38:17"
uuid = "cdbe784e-e98d-474d-90a3-06b663bc39bc"
