[[commentary]]
quote='''
What is the special excellence of Joshua? His generalship, and the distribution of the inheritance, and the taking possession of the Holy Land.
'''
source_url=''
source_title="ON BASIL THE GREAT, ORATION 43.72"
uuid = "3371beaa-e4e8-4d50-b4b9-cd5a4147d30a"
