[[commentary]]
quote='''
Who sustains us? Christ Jesus, the Word and Wisdom of God. Moreover, he sustains us not merely for a day or two, but forever.
'''
source_url=''
source_title="COMMENTARY ON 1 CORINTHIANS 1.2.52-54"
uuid = "dd79433f-f96e-4924-bf71-23db5df6ca16"
