[[commentary]]
quote='''
In this life the righteous person does not yet enjoy what he hopes for but rather endures suffering and danger. He is waiting for the revelation of Christ to come.
'''
source_url=''
source_title="COMMENTARY ON 1 CORINTHIANS 1.2.48-51"
uuid = "aa7d485b-f99d-4651-a525-60fa1f639836"
