[[commentary]]
quote='''
Let no one say: "I was young. Before I got married, I slept with prostitutes." Why did you not get married instead?
'''
source_url=''
source_title="COMMENTARY ON 1 CORINTHIANS 2.27.48-49"
uuid = "20b6f5b8-3ef2-4ee1-9a9f-b2d795ec3941"
