[[commentary]]
quote='''
Paul attacks the Corinthians because, although they are right in the middle of Greece, they have no truly wise people in their midst, even though many had gone to preach wisdom to them.
'''
source_url=''
source_title="COMMENTARY ON 1 CORINTHIANS 2.27.20-22"
uuid = "0dc7a4c7-6280-4276-a3ad-79c68a60346a"
