[[commentary]]
quote='''
People who insult others are said to slander or blaspheme against those whom they insult.… One blasphemes when one makes a true doctrine appear false or a false one true, especially when one speaks of God or matters pertaining to God.
'''
source_url=''
source_title="EPISTLE TO THE EPHESIANS"
uuid = "e47ae2ae-ea58-44e4-a37d-ccb3f089683a"
