[[commentary]]
quote='''
O you who are subject to pain, do not go into exile with mourning.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 10:1"
uuid = "42ffcbba-79f6-44e2-843f-debb89e15a83"


[[commentary]]
quote='''
It is an infamy to be separated from the people of God and from the church; it is a dishonor in the church to leave the bench of presbyters, to be expelled from the rank of the diaconate.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 10:1"
uuid = "b9f0694f-4c89-41fb-a1ad-2909396743ec"


[[commentary]]
quote='''
If we justify providence, we cleanse our disgrace; but if we do not receive the judgments of God, we will multiply our disgrace.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 10:1"
uuid = "44e2ad1c-2c3a-4fab-bc36-a4ea60ff371e"


[[commentary]]
quote='''
The more we come very near to God the more we come near the beatitude; and when we have sinned, we shall be far from it and very near terrible and very great punishments.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 10:2"
uuid = "b2e023cd-dd65-4e75-a54e-2fd0f2df9604"


[[commentary]]
quote='''
The person who is "very small" deserves mercy more quickly.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 10:2"
uuid = "fa3da06b-986b-4b4d-aef0-6893a571a645"
