[[commentary]]
quote='''
These various clothes and beautiful garments that God has bestowed on us, if we cut them up and rip them and surround them with false teaching to deceive human beings, there is no doubt that we are covering idols with different clothing.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 7:3"
uuid = "5daa3ed6-bda9-43bc-b256-ddadf42b4cbd"


[[commentary]]
quote='''
To me who preaches the gospel in the church, the devil always stretches out a noose, in order to confuse the whole church with my conduct.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 7:3"
uuid = "3b8f0a0d-c14e-4291-b896-152067abe625"


[[commentary]]
quote='''
We do not imitate anyone, but if we want to imitate anyone, we should imitate Jesus Christ.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 7:3"
uuid = "c983704f-2ac8-4567-b3a2-547e7cb946fa"


[[commentary]]
quote='''
Incense and oil are the prayer that is offered to God with understanding and in which God delights.
'''
source_url=''
source_title="EXCERPTS ON EZEKIEL 16:18"
uuid = "ac380c14-eb1d-4b93-acd6-c9bee8af9cda"


[[commentary]]
quote='''
Whoever is born in the teaching of heretics and has taken these principles for his own faith is a child of Jerusalem the fornicator and sinner.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 7:5"
uuid = "be98b48d-803c-463b-8a41-4862b7112eee"
