[[commentary]]
quote='''
Consider the sublime grandeur of the church of Christ, to understand that according to the promise of God the word has been realized.… It will become a noble cedar; and under it will dwell all kinds of beasts; in the shade of its branches birds of every sort will nest.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 12:5"
uuid = "45474166-01bb-40c4-8f02-9ea34be672ef"


[[commentary]]
quote='''
Take the wings of the word of God, and you will be able to repose under this tree that has been planted over a high mountain.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 12:5"
uuid = "4f676aac-d816-4775-adc8-25a53cae0e1d"
