[[commentary]]
quote='''
Which of the cities in the world were so elevated and so deep in knowledge as the city of God?
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 6:3"
uuid = "16de7712-8b2d-415b-ae5b-856a40fc7598"


[[commentary]]
quote='''
If so many things are said in Jerusalem about which such great and wonderful things are written that have been promised to her, what future is there for unhappy me, if I sin? Who will I have for a father, who will I have for a mother?
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 6:3"
uuid = "5f1a2dce-95e5-4b51-b112-121727c8c500"
