[[commentary]]
quote='''
False prophets are teachers of the church whose words or life do not properly accord with the doctrine that they preach.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 2:1"
uuid = "2452c4a0-c023-4ed4-bd40-a0989f3f7ff9"


[[commentary]]
quote='''
If the Word of God accuses me, I will try to be converted.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 2:2"
uuid = "59f582d9-f703-4eee-b827-2db2e1b865a4"


[[commentary]]
quote='''
The word of the present can agree with those who teach in the church, as long as they do not teach other than what the truth demands.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 2:2"
uuid = "441f3be8-2a98-4a71-bcf1-adf64363dce9"


[[commentary]]
quote='''
If anyone reading the gospel fits its proper sense to the gospel without understanding that the Lord speaks, he is a false prophet speaking according to his own heart in the gospel.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 2:2"
uuid = "2f058950-87de-4922-8c3b-003ae1f02ba6"


[[commentary]]
quote='''
If I find in Moses and the prophets the thought of Christ, I speak not according to my own heart but from the Holy Spirit.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Ezekiel%2FTranslation-Hooker-Pearse.pdf'
source_title="HOMILIES ON EZEKIEL 2:2"
uuid = "fc8a30be-e25c-4e40-b976-5173cac96b62"
