[[commentary]]
quote='''
By the holy place is to be understood every saying of divine Scripture spoken by the prophets from Moses onwards, and by the Evangelists and apostles. In this holy place of all the Scriptures, Antichrist, the false Word, has often stood. This is the abomination of desolation.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FCommentary%2520on%2520Matthew%2FIntroduction.html'
source_title="COMMENTARY ON MATTHEW 42"
uuid = "9b949cb1-c466-41cb-b8ac-7e9b464d6272"


[[commentary]]
quote='''
He who flees ought to know the place to which he ought to flee, and also to pray that he may not flee in the time which is opposed to flight.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FCommentary%2520on%2520Matthew%2FIntroduction.html'
source_title="COMMENTARY ON MATTHEW 41"
uuid = "89259be3-b736-4098-b524-7da371126d5f"
