[[commentary]]
quote='''
The kingdom of heaven is Jesus the Christ himself, who exhorts all people to repentance and draws them to himself by love.
'''
source_url=''
source_title="FRAGMENT 226"
uuid = "94590eb9-4a70-41c2-bc54-1685b50a3ab8"
