[[commentary]]
quote='''
"But the iniquitous shall be exterminated together", that is, all alike shall be exterminated, because there shall be one end for them, Gehenna. "The remnants of the impious shall perish", then when he who has the power shall give over both body and soul, destroyed, into Gehenna.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Origen%2520of%2520Alexandria%2FHomilies%2520on%2520Psalms%252036-38%2FHomily05.html'
source_title="HOMILIES ON PSALMS 37, HOMILY V"
