default_year=130
wiki='https://en.wikipedia.org/wiki/Papias_of_Hierapolis'
uuid = "eccb9e79-7bee-405d-b059-00d4c5a39b6b"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/6/63/Papias.png"
summary = "Papias or Papias of Hierapolis was a Greek Apostolic Father, Bishop of Hierapolis, and author who lived c. AD 60 – c. 130. He is mainly known for gathering oral stories about Jesus and his disciples, which he compiled in a now-lost five-volume work titled Exposition of the Sayings of the Lord. Brief excerpts of this work appear in the works of Irenaeus of Lyons and Eusebius of Caesarea. They are considered an important early source on Christian oral tradition and especially on the origins of the canonical Gospels."
