[[commentary]]
quote='''
But let not your fasts be with the hypocrites; for they fast on the second and fifth day of the week; but do ye fast on the fourth day and the Preparation (Friday).
'''
source_url='https://historicalchristian.faith/by_father.php?file=Didache%2FDidache.html'
source_title="The Didache, Chapter 8"
uuid = "3700d4ef-3768-4cdd-93e3-a21479d67fd8"
