default_year=100
wiki='https://en.wikipedia.org/wiki/Didache'
uuid = "90c39994-c2c7-475b-b94a-66215c5d06cf"
category = "Apocrypha, Documents & Liturgies"
image = "https://download.biblians.com/commentaries/fathers/Didache.webp"
summary = "The Didache, also known as The Lord's Teaching Through the Twelve Apostles to the Nations, is a brief anonymous early Christian treatise written in Koine Greek, dated by modern scholars to the first or second century AD."
