default_year=328
wiki='https://en.wikipedia.org/wiki/Pope_Alexander_I_of_Alexandria'
uuid = "dd1721c3-ca54-42d3-bb45-5c23897d6123"
category = "Early Fathers"
image = "https://upload.wikimedia.org/wikipedia/commons/e/ec/Veljusa_Monastery_St._Alexander_of_Alexandria.jpg"
summary = "Alexander I of Alexandria was the 19th Patriarch of Alexandria. During his patriarchate, he dealt with a number of issues facing the Church in that day. These included the dating of Easter, the actions of Meletius of Lycopolis, and the issue of greatest substance, Arianism. He was the leader of the opposition to Arianism at the First Council of Nicaea. He also mentored his successor, Athanasius of Alexandria, who would become one of the Church Fathers. He is regarded as a Pope by the Coptic Orthodox Church but not by the Catholic Church."
