[[commentary]]
quote='''
God in the Old Testament expostulates with men on the basis of their own conceptions of gratitude, fidelity, and fair play: and puts Himself, as it were, at the bar before His own creatures--"What iniquity have your fathers found in me, that they are gone far from me?"
'''
source_url=''
source_title="The Problem of Pain, Ch. 3"
uuid = "38aec450-0d8e-4680-a579-72145f515d73"
