default_year=190
wiki='https://en.wikipedia.org/wiki/Athenagoras_of_Athens'
uuid = "be0c952f-eb4c-45f5-872f-5d1637742cf1"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/6/62/Greek_Icon_of_Saint_Athenagoras_of_Athens.jpg"
summary = "Athenagoras was an Ante-Nicene Church Father, a Christian apologist who lived during the second half of the 2nd century of whom little is known for certain, besides that he was Athenian, a philosopher, and a convert to Christianity."
