default_year=132
wiki='https://en.wikipedia.org/wiki/Epistle_of_Barnabas'
uuid = "893a9533-9a6f-4373-ad01-454cf1171f3c"
category = "Apocrypha, Documents & Liturgies"
image = "https://upload.wikimedia.org/wikipedia/commons/4/49/Codex_Tchacos_p33.jpg"
summary = "The Epistle of Barnabas is an early Christian Greek epistle written between 70 and 135 AD. The complete text is preserved in the 4th-century Codex Sinaiticus, where it is positioned at the end of the New Testament, following the Book of Revelation and preceding the Shepherd of Hermas."
