[[commentary]]
quote='''
Now our rod is the Word of God, Jesus Christ, as Jeremiah saw him as an almond rod. So everyone that spares his son a word of rebuke hates his son. Therefore teach your sons the word of the Lord. Punish them with lashes. Subdue them by your word of religion from their youth.
'''
source_url=''
source_title="DIDASCALIA 22.[4:11]"
uuid = "8469a615-6fc0-4736-a93c-516cd539c19c"
