default_year=230
wiki='https://en.wikipedia.org/wiki/Didascalia_Apostolorum'
uuid = "bb8a2799-9a4c-43aa-89c3-368e54701d83"
category = "Apocrypha, Documents & Liturgies"
summary = "Didascalia Apostolorum, or just Didascalia, is an early Christian legal treatise which belongs to the genre of the Church Orders. It presents itself as being written by the Twelve Apostles at the time of the Council of Jerusalem; however, scholars agree that it was actually a later composition, with most estimates suggesting the 3rd century, and other estimates suggesting potentially as late as the 4th century."
