[[commentary]]
quote='''
Why is the lamb offered up in the evening and not during the day? The reason is plain enough, for our Lord and Savior suffered his passion at the close of the ages, which is why John called it the last hour.
'''
source_url=''
source_title="SERMONS 91"
uuid = "001a10e0-75be-42ac-83da-5f1cf14c1d35"
