[[commentary]]
quote='''
The word cry in Scripture does not refer to the cry of the voice but to the cry of the heart. In fact, the Lord says to Moses, "Why are you crying out to me?" when Moses had not muttered any cry at all.
'''
source_url=''
source_title="HOMILIES ON THE PSALMS 2"
uuid = "242d771b-456a-4886-8aa9-a8af81b833ce"
