[[commentary]]
quote='''
I myself will go to the shepherds and will seek out my flock from the hand of those who find it convenient to have a millstone placed around their neck.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 11:34.1-31"
uuid = "027ab079-3679-4a34-8fac-66416228b2e6"
