[[commentary]]
quote='''
In case this seems to be difficult I will come to you; I who have turned away from you will turn my face toward you, so that you may have the cultivation that you once had and that everything may be filled with seed. In this way there will be many people among you, and the cities that were once destroyed will be inhabited once again.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 11:36.1-15"
uuid = "7f2aa14c-175f-4e67-86dd-90952303e41d"


[[commentary]]
quote='''
We say that the mountains of Israel, the prophets and the apostles, are those who hear the Word of God and are those to whom the devil is an enemy and against whom he scoffs.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 11:36.1-15"
uuid = "5826b3cb-06ed-4727-aa70-df8702d3b4e9"
