[[commentary]]
quote='''
When the animals stand, their wings are set down. For they are not able to bear the voice of the Lord sounding in the heavens, but they stand and marvel, and they show by their silence the power of God, who sits above the firmament.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 1:1.22-26"
uuid = "77c1a2a3-c0e7-4cd6-a564-84550fe4a1b9"
