[[commentary]]
quote='''
This word is rightly directed against Israel, so that they might repent and leave behind their iniquities, their transgressions, with which they have sinned against God.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 6:18.30-31"
uuid = "f54163e9-2b96-4e0a-bea1-8298ab096813"

[[commentary]]
quote='''
These words show us that the mind must not fail to believe in the promised blessings and give way to despair; and the soul once marked out for perdition must not refuse to apply remedies on the ground that its wounds are past curing.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome/Letters/letter_122.html'
source_title="LETTER 122.1"
uuid = "c6fe3e86-f12e-4e33-8ca8-e87917678a5c"


[[commentary]]
quote='''
(Verse 30.) Therefore, I will judge each one according to their ways, O house of Israel, says the Lord God. Whether they are from the multitude of nations or from the people of Israel who are being judged: God does not show partiality (Colossians 3:25), but each one will be rewarded according to their faith, and will be condemned for their wickedness and unbelief.
'''
source_url='https://historicalchristian.faith/by_father.php?file=Jerome%2FCommentary%2520on%2520Ezekiel.html'
source_title="Commentary on Ezekiel"
uuid = "06618a34-40d9-4312-a0b1-c0c9b557f516"
