[[commentary]]
quote='''
Why should I speak of only one people? If I send you to different nations, my authority and power will still overcome every difficulty.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 1:3.5-6"
uuid = "8b005287-73b4-40a0-83df-5a473653cbc2"
