[[commentary]]
quote='''
You must not imitate those whom you are sent to correct, in case the same sin should merit exactly the same punishment.
'''
source_url=''
source_title="COMMENTARY ON EZEKIEL 1:2.8"
uuid = "da6ae4e2-7066-4c21-8b1d-b7c0b7fabb39"
