[[commentary]]
quote='''
By "years" I think he means the seventh year of release, and the fiftieth, which they call the jubilee.
'''
source_url=''
source_title="EPISTLE TO THE GALATIANS 2.4.10-11"
uuid = "e17050ed-15a4-4053-b943-670e59cb18f7"
