[[commentary]]
quote='''
In the Gospel, according to John, there is found in many of both the Greek as well as the Latin copies, the story of the adulteress who was accused before the Lord.
'''
source_url='https://www.newadvent.org/fathers/30112.htm'
source_title="Against the Pelagians 2.17"
uuid = "85c3b2db-b177-4a9e-9905-5f20f77bbfc5"
