[[commentary]]
quote='''
"You have taken my friends away from me." In the passion of the cross, even my apostles fled from me; so completely did they shun me that Peter himself said: "I do not know this man."
'''
source_url=''
source_title="HOMILIES OF SAINT JEROME, HOMILY 65"
uuid = "ed736de9-0833-40a3-9f37-70d9f95cf8d2"
