[[commentary]]
quote='''
He says not "you are" but "so that you may be," deferring it to the future and not asserting it as a present fact, to show that here there is toil and struggle and there the rewards of toil and virtue.
'''
source_url='https://www.newadvent.org/fathers/30113.htm'
source_title="Against the Pelagians 3.13"
uuid = "53d92326-ff88-4a54-a87d-86af9e9c2511"
