[[commentary]]
quote='''
This psalm can pertain to David or to Christ, and through him to all the saints.
'''
source_url=''
source_title="BRIEF COMMENTARY ON PSALM 3"
uuid = "1fd4a31c-c95f-4bbe-9ad3-0a66b8b5638e"
