[[commentary]]
quote='''
The ungodly without the law shall perish forever. But the sinner under the law who comes to faith in God will not perish.
'''
source_url='https://www.newadvent.org/fathers/30111.htm'
source_title="Against the Pelagians 1.28"
uuid = "5a7ae8db-173a-4796-868e-93381bea0088"
