[[commentary]]
quote='''
Let us live our lives in the same way now as we are going to live in the day, that is, in the future world.
'''
source_url=''
source_title="HOMILIES ON THE PSALMS 46"
uuid = "03105de5-f227-49b4-8ed0-67fb36f8f6e8"
