[[commentary]]
quote='''
God alone is wise, although both Solomon and many other holy men were called wise.
'''
source_url='https://www.newadvent.org/fathers/30112.htm'
source_title="Against the Pelagians 2.7"
uuid = "a1c499df-3bb2-4a30-9447-a7532e730b53"
