[[commentary]]
quote='''
Paul shows clearly that righteousness depends not on the merit of man but on the grace of God, who accepts the faith of those who believe without the works of the law.
'''
uuid = "4d8a08bf-0eeb-431f-b9eb-b4f9a9d60727"
