default_year=942
wiki='https://en.wikipedia.org/wiki/Agapius_of_Hierapolis'
uuid = "a5beab68-0c08-4c56-a68b-c74cae933cac"
category = "Syriac & Oriental Theology"
summary = "Agapius of Hierapolis, also called Maḥbūb ibn Qusṭanṭīn, was a Melkite Christian historian and the bishop of Manbij in Syria. He wrote a universal history in Arabic, the lengthy Kitāb al-ʿunwān. He was a contemporary of the annalist Eutychius, also a Melkite."
