default_year=600
wiki='https://en.wikipedia.org/wiki/Paschasius_of_Dumium'
uuid = "317ef29b-205b-4ec9-ac8b-b87e5e664f2c"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/Bodleian_Library_MS._Laud_Misc._346,_folio_92v.webp"
summary = "Paschasius of Dumium was a monk of Dumium in the Suevic kingdom of Gallaecia who translated the Sayings of the Desert Fathers from Greek into Latin."
