default_year=400
wiki='https://en.wikipedia.org/wiki/Book_of_Steps'
uuid = "f401abf7-a05e-461c-80cc-a05ce7fbdea9"
category = "Apocrypha, Documents & Liturgies"
summary = "The Book of Steps is an anonymous treatise and a work of Christian Syriac literature, probably written in the late fourth century AD. The author appears to be living in the Sasanian Empire, perhaps somewhere near the Lesser Zab, as it is mentioned in Memra Thirty, and addresses the author's own Christian community."
