[[commentary]]
quote='''
At the end of every letter he wrote his name both in Hebrew letters and in the Greek, lest what may come from one of the false apostles may be allowed to corrupt them.
'''
uuid = "c53df042-afff-48b5-86b9-00b212b81fa2"
