[[commentary]]
quote='''
He prepared the fish, that is, He made it come next to the ship, in order that it might take Jonah in its mouth when he was thrown overboard.
'''
uuid = "ed3b6955-b94e-4970-8782-e3da6565105a"
