default_year=203
wiki='https://en.wikipedia.org/wiki/The_Passion_of_Saints_Perpetua_and_Felicity'
uuid = "642c9955-97d7-40ba-8d18-2f4affe824ed"
category = "Apocrypha, Documents & Liturgies"
image = "https://upload.wikimedia.org/wikipedia/commons/3/31/Passio_sanctarum_Perpetuae_et_Felicitatis.jpg"
summary = "The Passion of Saints Perpetua and Felicity is a diary by Vibia Perpetua describing her imprisonment as a Christian in 203, completed after her death by a redactor. It is one of the oldest and most notable early Christian texts."
