default_year=155
wiki='https://en.wikipedia.org/wiki/Polycarp'
uuid = "0572f833-622d-4631-8193-50701e1e3280"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/f/f1/Polycarp_of_Smyrna2.jpg"
summary = "Polycarp was a Christian bishop of Smyrna. According to the Martyrdom of Polycarp, he died a martyr, bound and burned at the stake, then stabbed when the fire failed to consume his body. Polycarp is regarded as a saint and Church Father in the Eastern Orthodox Church, the Catholic Church, Oriental Orthodox Churches, Lutheranism, and Anglicanism."
