default_year=-300
wiki='https://en.wikipedia.org/wiki/Book_of_Enoch'
uuid = "9a261267-5cac-482c-9244-fdc47120c778"
category = "Apocrypha, Documents & Liturgies"
image = "https://upload.wikimedia.org/wikipedia/commons/a/a7/BL_Or_485_f._102r.png"
summary = "The Book of Enoch is an ancient Jewish apocalyptic religious text, ascribed by tradition to the patriarch Enoch who was the father of Methuselah and the great-grandfather of Noah. The Book of Enoch contains unique material on the origins of demons and Nephilim, why some angels fell from heaven, an explanation of why the Genesis flood was morally necessary, and a prophetic exposition of the thousand-year reign of the Messiah. Three books are traditionally attributed to Enoch, including the distinct works 2 Enoch and 3 Enoch."
