default_year=202
wiki='https://en.wikipedia.org/wiki/Irenaeus'
uuid = "5891a99d-d6ba-482c-b6f1-2d4450269a08"
category = "Early Fathers (Pre-Nicaea)"
image = "https://download.biblians.com/commentaries/fathers/Saint_irenee_saint_irenee.webp"
summary = "Irenaeus was a Greek bishop in the second century, noted for his role in guiding and expanding Christian communities in the southern regions of present-day France and, more widely, for the development of Christian theology by opposing Gnostic interpretations of Christian Scripture and defending orthodoxy. Originating from Smyrna, he had seen and heard the preaching of Polycarp, who in turn was said to have heard John the Evangelist."
