[[commentary]]
quote='''
We do not get good laws to restrain bad people. We get good people to restrain bad laws.
'''
source_url=''
source_title="All Things Considered, Thoughts Around Koepenick (1908)"
uuid = "f0ff9390-99ba-47f5-baa9-0f4cdcd4fd04"

[[commentary]]
quote='''
The vitality and recurrent victory of Christendom have been due to the power of the Thing to break out from time to time from its enveloping words and symbols. Without this power all civilisations tend to perish under a load of language and ritual. One instance of this we hear much in modern discussion: the separation of the form from the spirit of religion. But we hear too little of numberless other cases of the same stiffening and falsification; we are far too seldom reminded that just as church-going is not religion, so reading and writing are not knowledge, and voting is not self-government.
'''
source_url=''
source_title="A Miscellany of Men, The Thing (1912)"
uuid = "0a19c48d-ef65-4ff3-94b1-1769974d9c6b"
