[[commentary]]
quote='''
For in so far as drinking is really a sin it is not because drinking is wild, but because drinking is tame; not in so far as it is anarchy, but in so far as it is slavery. Probably the worst way to drink is to drink medicinally. Certainly the safest way to drink is to drink carelessly; that is, without caring much for anything, and especially not caring for the drink.
'''
time=1908
source_url=''
source_title="Wine When It Is Red (All Things Considered)"
uuid = "93d6684b-ed4e-481a-83ec-be168229e2b6"

[[commentary]]
quote='''
A Free Lover is worse than a profligate. For a profligate is serious and reckless even in his shortest love; while a Free Lover is cautious and irresponsible even in his longest devotion.
'''
source_url=''
source_title="Tremendous Trifles, The Diabolist (1909)"
uuid = "44c1b7f6-0257-4bcb-969e-fbf384a80eb4"
