[[commentary]]
quote='''
"God is love." Wherefore, the man who lives in love reaps the fruit of life from God, and while yet in this world, he even now breathes the air of the resurrection.
'''
source_url=''
source_title="ASCETICAL HOMILIES 46"
uuid = "98b0944e-d890-4b4d-bff9-7424130ae78b"
