[[commentary]]
quote='''
The image of Christ is formed in us through the Spirit of wisdom and the revelation of the knowledge of Him.
'''
source_url=''
source_title="ASCETICAL HOMILIES 37"
uuid = "c3b08ffc-2219-4926-bceb-ffbeec0de368"
