default_year=1198
wiki='https://en.wikipedia.org/wiki/Nerses_of_Lambron'
uuid = "f62d0aa5-f25f-45af-9d89-e738e2b340e2"
category = "Syriac & Oriental Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/0/05/Nerses_Lambronatsi.jpg"
summary = "Saint Nerses of Lambron (1153–1198) was the Archbishop of Tarsus in the Armenian Kingdom of Cilicia who is remembered as one of the most significant figures in Armenian literature and ecclesiastical history."
