[[commentary]]
quote='''
first begotten of the dead. Because he is not like those who died previously and rose and died again; but he is eternally immortal in the body which died.
'''
uuid = "9e6546e2-a8b8-4fe4-9131-3dcfc2f57d10"

