default_year=439
wiki='https://en.wikipedia.org/wiki/Socrates_of_Constantinople'
uuid = "b13fc217-8e43-47cd-aee4-5ad28ddea297"
category = "Eastern & Byzantine Theology"
summary = "Socrates of Constantinople, also known as Socrates Scholasticus, was a 5th-century Greek Christian church historian, a contemporary of Sozomen and Theodoret."
