default_year=439
wiki='https://en.wikipedia.org/wiki/Socrates_of_Constantinople'
uuid = "d83655f7-2617-42b7-9fe8-84ea5e437c17"
category = "Eastern & Byzantine Theology"
summary = "Socrates of Constantinople, also known as Socrates Scholasticus, was a 5th-century Greek Christian church historian, a contemporary of Sozomen and Theodoret."
