default_year=1153
wiki='https://en.wikipedia.org/wiki/Bernard_of_Clairvaux'
uuid = "592918f7-ecbc-4cb5-9252-d40d56bf4e63"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/San_Bernardo,_de_Juan_Correa_de_Vivar_(Museo_del_Prado).webp"
summary = "Bernard of Clairvaux, O.Cist., venerated as Saint Bernard, was an abbot, mystic, co-founder of the Knights Templar, and a major leader in the reform of the Benedictines through the nascent Cistercian Order."
