[[commentary]]
quote='''
Paul says this in order to show that the Romans too, made up as they were of all the nations inhabiting the world, rightly accepted the preaching of his message.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "ca512e6c-be3f-491a-bbc4-2fe172abf1df"
