default_year=609
wiki='https://en.wikipedia.org/wiki/Venantius_Fortunatus'
uuid = "0db57e4c-447c-4469-b2ee-d6cb2d5641cc"
category = "Western & Medieval Theology"
image = "https://upload.wikimedia.org/wikipedia/en/5/52/Poitiers%2C_M%C3%A9diath%C3%A8que_Fran%C3%A7ois_Mitterrand%2C_MS_250_%28136%29%2C_fol._21v.jpg"
summary = "Venantius Honorius Clementianus Fortunatus, known as Saint Venantius Fortunatus, was a Latin poet and hymnographer in the Merovingian Court, and a Christian bishop who has been venerated since the Middle Ages."
