[[commentary]]
quote='''
This is wisdom, and this is the mystery of the Supreme God. God willed that He should be acknowledged and worshipped through Him.
'''
uuid = "fcba8077-245d-45fe-9e47-90916ac92c67"
