[[commentary]]
quote='''
-testify that He was born of God. His name is known to none, except to Himself and the Father, as John teaches in the Revelation.
'''
uuid = "670282d9-b4d6-45d0-99bf-5d62bcfb3189"

