default_year=235
wiki='https://en.wikipedia.org/wiki/Pope_Pontian'
uuid = "ff6c69d4-bcf4-4d00-9804-342dfec9bff7"
category = "Early Fathers (Pre-Nicaea)"
image = "https://upload.wikimedia.org/wikipedia/commons/4/4d/Spinello_Aretino_008.jpg"
summary = "Pope Pontian was the bishop of Rome from 21 July 230 to 28 September 235. In 235, during the persecution of Christians in the reign of the Emperor Maximinus Thrax, Pontian was arrested and sent to the island of Sardinia."
