default_year=9999
wiki='https://en.wikipedia.org/wiki/Pseudo-Jerome'
uuid = "043aa685-22b1-49b0-af6c-b5e2263a0282"
category = "Apocrypha, Documents & Liturgies"
summary = 'Pseudo-Jerome is the name given to several authors misidentified as, or pseudepigraphically claiming to be, Saint Jerome. A principal writing identified as "Pseudo Jerome" is the ninth-century writing the Epistle of Pseudo-Jerome to Paula and Eustochium, a sermon on the Assumption of Mary.'
