default_year=9999
wiki='https://en.wikipedia.org/wiki/Pseudo-Jerome'
uuid = "b1959924-ee3d-4fca-b307-f1b11e80cbfe"
category = "Apocrypha, Documents & Liturgies"
summary = 'Pseudo-Jerome is the name given to several authors misidentified as, or pseudepigraphically claiming to be, Saint Jerome. A principal writing identified as "Pseudo Jerome" is the ninth-century writing the Epistle of Pseudo-Jerome to Paula and Eustochium, a sermon on the Assumption of Mary.'
