default_year=180
wiki='https://en.wikipedia.org/wiki/Hegesippus_(chronicler)'
uuid = "716b5831-8e05-417b-81e8-a5dfd5c43ddc"
category = "Early Fathers"
image = "https://upload.wikimedia.org/wikipedia/commons/5/58/Hegesippus_Egesippus_Nuremberg_Chronicle_cropped.png"
summary = "Hegesippus, also known as Hegesippus the Nazarene, was a Christian writer of the early Church who, in spite of his Greek name, may have been a Jewish convert and certainly wrote against heresies of the Gnostics and of Marcion."
