[[commentary]]
quote='''
"Now the weak eateth herbs," according to the noble apostle.
'''
source_url="https://historicalchristian.faith/by_father.php?file=Clement%2520of%2520Alexandria%2FThe%2520Stromata%2520Book%25206.html"
source_title="The Stromata Book 6"
uuid = "dc1801ac-0ec3-4b71-8b01-01a14c554770"
