[[commentary]]
quote='''
So then, my brothers, let us strive, knowing that the contest is close at hand and that many make voyages for corruptible contests, but not all are crowned—only those who have labored much and striven well.
'''
source_url=''
source_title="2 Clement 7"
uuid = "f82fce1e-74e8-4da0-bff1-7a86fc233552"

