[[commentary]]
quote='''
chain. By this is the great quantity of his power represented.
'''
uuid = "d9d9d83c-34a4-41ab-ae92-b43c1c03e2b6"

[[commentary]]
quote='''
key to the bottomless pit. this is because he has in his power the hearts of those whom he hardens, and of those whom he opens to believing. The bottomeless pit is the great number of the faithful peoples, because just as it is incomprehensible, so also is the great number of peoples.
'''
uuid = "6b4185cb-d8a9-4101-9387-f4853aee5095"

[[commentary]]
quote='''
an angel. That angel is the Lord Jesus Christ, an angel of great prudence, who decended from heaven through the mystery of the Incarnation.
'''
uuid = "a74c5554-2a85-4b6a-8114-c26e23928ca2"

