[[commentary]]
quote='''
A hermit said, 'A monk ought not to listen to disparagement; he ought not to be disparaging, and he ought not to be scornful.'
'''
source_url='https://books.google.com/books/about/The_Desert_Fathers.html?id=UkbZy7-SqjkC'
source_title="The Desert Fathers, Sayings of the Early Christian Monks"
uuid = "6b9f2d10-45ce-42f0-ab99-8386be8a3c7b"
