[[commentary]]
quote='''
The view that this paenula is some other kind of book, rather than just a garment, is ridiculous.
'''
source_url=''
source_title="COMMENTARY ON 2 TIMOTHY"
uuid = "d74aa635-4f6e-49b5-987c-3698899d839c"


[[commentary]]
quote='''
Paul makes a distinction here between the parchment volumina, which are in the form of scrolls, and the regular libros, which are in book or codex form.
'''
source_url=''
source_title="COMMENTARY ON 2 TIMOTHY"
uuid = "5f034ec2-9a4c-4482-b1df-d2aa83f38121"
