[[commentary]]
quote='''
Nicodemus, either out of weakness or fear of the doctors, did not reply to them when they wanted to diminish the words and works of Christ by mentioning Galilee.
'''
source_url=''
source_title="COMMENTARY ON JOHN 3.7.52"
uuid = "a3895a28-da8c-4361-8ff0-1fb9147e4fc5"
