[[commentary]]
quote='''
Perhaps his mother, as mothers do, incited him to perform a miracle, wishing that the greatness of her son would be revealed—and thinking that the lack of wine offered the right occasion for the miracle.
'''
source_url=''
source_title="COMMENTARY ON THE GOSPEL OF JOHN 1.2, 3"
uuid = "6b5745a8-a87b-48e0-bef2-5fac53c0709a"
