default_year=428
wiki='https://en.wikipedia.org//wiki/Theodore_of_Mopsuestia'
uuid = "b5a5e878-432a-4c9a-987b-4b305d774b52"
category = "Eastern & Byzantine Theology"
image = "https://download.biblians.com/commentaries/fathers/Jerusalem_Holy-Sepulchre_Jesus-Detail-01.webp"
summary = "Theodore of Mopsuestia was a Christian theologian, and Bishop of Mopsuestia from 392 to 428 AD. He is also known as Theodore of Antioch, from the place of his birth and presbyterate. He is the best known representative of the middle Antioch School of hermeneutics."
