[[commentary]]
quote='''
Now Paul uses the name of Onesimus, but only after signaling the profound change that has occurred [i.e., Onesimus's conversion].
'''
source_url=''
source_title="COMMENTARY ON PHILEMON"
uuid = "4a273c66-1d08-4bfd-94c3-edf78af8341f"
