[[commentary]]
quote='''
Paul makes a point of greeting Philemon and Apphia equally. He wishes to indicate thereby that in no way is there a difference of faith or strength of faith between men and women.
'''
source_url=''
source_title="COMMENTARY ON PHILEMON"
uuid = "0a7dfcda-5459-4b63-8176-d28f1258114f"


[[commentary]]
quote='''
Archippus was their son.
'''
source_url=''
source_title="COMMENTARY ON PHILEMON"
uuid = "757cc3ed-2175-42b3-acf3-39e0e4ab7c48"


[[commentary]]
quote='''
While keeping the social order here, Paul does not call some indiscriminate multitude "the church," but only those who are bound together in faith. This bond sets the frame for Paul's appeal in the letter.
'''
source_url=''
source_title="COMMENTARY ON PHILEMON"
uuid = "ca91c4f6-faf5-4a00-9a88-cb92f19a4ca4"
