[[commentary]]
quote='''
He wants devotion, not coercion … because to obey is more sublime than to yield simply to duty.
'''
source_url=''
source_title="COMMENTARY ON PSALMS 2:11"
uuid = "8bc281c1-0069-4e57-b7b2-78cd616d2fdf"
