[[commentary]]
quote='''
By "first fruits" Paul means Christ, because he was selected out of the entire race of the Jews; by "root" he means Abraham, from whom the race descended.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "979ec122-c8b7-4c8d-b919-d399669bc5b4"
