[[commentary]]
quote='''
By "embodiment" is meant not the form but the substance and the knowledge and the truth, like the one "who was in the form of God."
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "0f328d7e-d31b-4616-af97-c7d846fb4751"
