[[commentary]]
quote='''
The first part of this [verse] ought to be read as a question to which the second part is the apostle's answer.… There is nothing surprising about this, for Isaiah also testifies to the small number of believers.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "1116dced-2e3d-4c70-93f0-e0ddbf61730f"
