[[commentary]]
quote='''
It is perfectly clear to us, says Paul, following the voice of the prophet and what we have said, that there can be no faith without teaching, and the teaching of godliness is impossible unless it shows the truth about God.
'''
source_url=''
source_title="PAULINE COMMENTARY FROM THE GREEK CHURCH"
uuid = "7d0a0a07-9a2c-4280-9c8e-e39e22450391"
