[[commentary]]
quote='''
These are elders in age only, though some have taken the position that the women held an office analogous to that of male presbyters.
'''
source_url=''
source_title="COMMENTARY ON TITUS"
uuid = "870de559-7d30-4210-9f2b-892daace2fc0"


[[commentary]]
quote='''
The women are to be decently adorned, reverent and dignified.
'''
source_url=''
source_title="COMMENTARY ON TITUS"
uuid = "52027dd8-0de9-460e-99ea-a6dfd94d2883"
