[[commentary]]
quote='''
After Cain received the punishment and the sign had been added to it … Moses said that "Cain went away from the presence of the Lord and dwelt in the land of Nod, east of Eden." Cain, therefore, separated himself from his parents and his kin because he saw that they would not intermarry with him.
'''
source_url=''
source_title="COMMENTARY ON GENESIS 3.11.1"
uuid = "1b7b9ea9-4f35-4983-970a-e7302b62502f"


[[commentary]]
quote='''
The land of Nod is so called because it was the land in which Cain wandered about in fear and trembling. But the land also received a second curse when God said, "When you till the earth it shall no longer yield to you its strength."
'''
source_url=''
source_title="COMMENTARY ON GENESIS 3.11.1"
uuid = "f2762e41-0f06-40a4-a056-4e13b3e4c96a"


[[commentary]]
quote='''
There the families
of the two brothers had separated:
Cain went off by himself
and lived in the land of Nod,
a place lower still
than that of Seth and Enosh;
but those who lived on higher ground,
who were called
"the children of God,"
left their own region and came down
to take wives
from the daughters of Cain down below.
'''
source_url=''
source_title="HYMNS ON PARADISE 1.11"
uuid = "10e4ba10-f4ab-4895-ab0e-1674bcb6c921"
