[[commentary]]
quote='''
"Therefore, brethren, we have confidence to enter the sanctuary," which is faith. In his blood he renewed for us the way of faith that the former priests had already. But since it had become obsolete among them, he renewed it for us at that time "through the curtain, that is, through his flesh."
'''
source_url=''
source_title="COMMENTARY ON THE EPISTLE TO THE HEBREWS"
uuid = "3c2a0ffd-18e3-426f-b8cb-8fbd39e451d6"
