[[commentary]]
quote='''
Paul says, "through whom he made the worlds," that is, both the spiritual and material worlds.
'''
source_url=''
source_title="COMMENTARY ON THE EPISTLE TO THE HEBREWS"
uuid = "9200a740-8301-42c9-8f70-c8bc3f3d0f12"
