[[commentary]]
quote='''
They gain a profit from it: their reward is justice. Paul said this in order to prove that even though they gain a profit through discipline, their reward and grace is constituted by justice.
'''
source_url=''
source_title="COMMENTARY ON THE EPISTLE TO THE HEBREWS"
uuid = "27ca2b90-ef3a-4025-8693-d526c477bf6b"
