[[commentary]]
quote='''
Now the interpretation of the name Melchizedek is "king of justice" and "king of peace." The apostle indeed demonstrated that in this name the mystery of the grace and justice of the Son, Lord of Melchizedek, was inscribed.
'''
source_url=''
source_title="COMMENTARY ON THE EPISTLE TO THE HEBREWS"
uuid = "b290fac7-1468-4cd2-9bf8-4761559d2f36"
