[[commentary]]
quote='''
"If it is not so, may his wrath make me lie," that is, if sinners do not go into that scorn that I have mentioned before, may the wrath of God prove false what I have said.
'''
source_url=''
source_title="COMMENTARY ON JOB 24:25"
uuid = "3b25bec2-b306-4ea5-ad4c-2886ff2fbe96"
