[[commentary]]
quote='''
This means that you will be restored to your former state. And God will be your helper while before it seemed that he had completely neglected the care of your salvation, as if he had been absent.
'''
source_url=''
source_title="COMMENTARY ON JOB 22:23"
uuid = "927f9f84-7487-4184-8fc4-16391ff928f0"
