[[commentary]]
quote='''
The Behemoth is a dragon, that is, a land animal, just as the Leviathan is an aquatic sea animal.
'''
source_url=''
source_title="COMMENTARY ON JOB 40:15"
uuid = "c89c057c-2f00-4f2a-a18b-7fd092e7572f"
