[[commentary]]
quote='''
For Siloam did not open [the eyes of] the blind man, just as the waters of the Jordan did not purify Naaman, but rather it was the command [by our Lord] that brought the healing. Also, it is not the waters of our atonement that bring purification; rather, it is the names invoked over it that produce atonement for us.
'''
source_url=''
source_title="COMMENTARY ON TATIAN'S DIATESSARON 16.29"
uuid = "5afc9880-b1f4-4574-b5c3-9d2f59ec62a9"
