[[commentary]]
quote='''
The things that were hidden were revealed through him [our Lord], just as the secrets of the heart are made known by a word.
'''
source_url=''
source_title="COMMENTARY ON TATIAN'S DIATESSARON 1.2"
uuid = "d514fc94-e119-4f0e-9b1f-5bb1e07912c5"
