[[commentary]]
quote='''
"Untie the donkey and bring it to me." He began with a manger and finished with a donkey, in Bethlehem with a manger, in Jerusalem with a donkey.
'''
source_url=''
source_title="COMMENTARY ON TATIAN'S DIATESSARON 18.1"
uuid = "d5e2e64f-af60-40a3-93db-14b2d7408e70"
