[[commentary]]
quote='''
When you have done something good, remember the words, "without me you can do nothing."
'''
source_url=''
source_title="ON THE SPIRITUAL LAW 41"
uuid = "5cd44faa-e5e4-4c07-be61-8d18885d87d9"
