[[commentary]]
quote='''
But so that the saints be preferred.
'''
source_url='https://www.newadvent.org/fathers/0715.htm'
source_title="CONSTITUTIONS OF THE HOLY APOSTLES"
uuid = "8b72938e-e8b9-400f-bb95-8f7925e5c930"
