[[commentary]]
quote='''
He who then had forbidden murder now forbids anger without cause. He who had forbidden adultery now forbids all unlawful lust. He who had forbidden stealing now pronounces him most happy who supplies those that are in want out of his own labors. He who had forbidden hatred now pronounces him blessed who loves his enemies.
'''
source_url='https://www.newadvent.org/fathers/07156.htm'
source_title="CONSTITUTIONS OF THE HOLY APOSTLES 6.23"
uuid = "79ff5ce6-3b26-4030-b6b4-899eb782c4ce"
