[[commentary]]
quote='''
For this is God's command, that l you owe nothing to any one but the pledge of love, which God has commanded by Christ.
'''
source_url='https://www.newadvent.org/fathers/0715.htm'
source_title="CONSTITUTIONS OF THE HOLY APOSTLES"
uuid = "bf6f63f7-b736-45c3-a2d8-65edd18c2eb4"
