default_year=400
wiki='https://en.wikipedia.org/wiki/Karpasia_(town)'
uuid = "955c6b07-cdd4-463d-ae92-15654e1ec6f3"
category = "Eastern & Byzantine Theology"
image = "https://download.biblians.com/commentaries/fathers/Karpasia_-_Agios_Filon1.webp"
summary = "Karpasia, Latinized as Carpasia, and also known as Karpasion, was an ancient town in Cyprus, situated on the northern shore of the Karpas Peninsula, 3 km (1.9 mi) from the modern town of Rizokarpaso. According to tradition, it was founded by the Phoenician king Pygmalion of Tyre. It had a harbour, whose moles remain visible to this day."
