[[commentary]]
quote='''
And there appeared to them separate tongues: 
So then, the thorns were consumed, that is, the transgression from Adam was consumed.
'''
uuid = "e2247f27-3c6f-4498-8f4d-979a7fb6d50b"
