[[commentary]]
quote='''
Those who are stronger and are not troubled by scruples are nevertheless commanded to abstain so as not to offend those who, on account of their weakness, still find abstinence necessary.
'''
source_url=''
source_title="THE WAY OF LIFE OF THE CATHOLIC CHURCH 71"
uuid = "a9727d0a-341b-4157-a480-31be5c224d59"
