[[commentary]]
quote='''
The history of the exodus was an allegory of the Christian people that was yet to be.
'''
source_url=''
source_title="THE USEFULNESS OF BELIEF 8"
uuid = "67d40691-097d-4269-8e87-d4c921ddf5d7"
