[[commentary]]
quote='''
Paul says that they have been changed for the better, not so as to lose concupiscence altogether, a condition never realized in this life, but so as to not obey the desire to sin.
'''
source_url=''
source_title="AGAINST JULIAN 16.49"
uuid = "cd41b425-667a-4e1a-b2f6-6d14959ee4f0"
