[[commentary]]
quote='''
Indeed, it is said that Beelzebub means prince of flies; and it has been written of them, "Dying flies spoil the sweetness of the oil."
'''
source_url=''
source_title="TRACTATES ON THE GOSPEL OF JOHN 1:14.3"
uuid = "4f27aa03-b6c3-4cbb-86ea-f1f6cd9d605a"
