[[commentary]]
quote='''
Both Haggai and Zechariah, the one within the year after the other, began to prophesy that which seemed to pertain to the restoration of the temple, as was foretold so long before. [EXPLANATION OF THE PSALMS 112.1]
'''
uuid = "753f2fa3-b768-431f-8b1e-24c12e665dc2"
