[[commentary]]
quote='''
Here discipline is spoken of in reference to those evils that anyone suffers for his sins in order that he may be corrected.
'''
source_url=''
source_title="ON THE TRINITY 14.1.1"
uuid = "38bdea59-a40b-4924-bd2b-69cbe1f8518e"
