[[commentary]]
quote='''
Does the one who does not know how to do good and does not do it commit a sin? He certainly does, but the one who knows what is good and does not do it sins more grievously.
'''
source_url=''
source_title="ADULTEROUS MARRIAGES 9"
uuid = "78bd5bfe-baa6-4c42-9fe9-0c2cd8882fc8"
