[[commentary]]
quote='''
You have been a paralytic inwardly. You did not take charge of your bed. Your bed took charge of you.
'''
source_url='https://www.newadvent.org/fathers/1801041.htm'
source_title="ON THE PSALMS 41.4"
uuid = "1c52c92f-6cb5-495c-887c-3ce45b7247e9"
