[[commentary]]
quote='''
By faith in Jesus Christ is granted to us both possession of the little beginning of salvation and its perfecting, which we await in hope.
'''
source_url=''
source_title="THE SPIRIT AND THE LETTER 51"
uuid = "055969f0-0afa-4fce-86dd-6525d68c1095"
