[[commentary]]
quote='''
The law is only a written code to those who do not fulfill it in the spirit of charity to which the New Testament belongs.
'''
source_url=''
source_title="TO SIMPLICIAN ON VARIOUS QUESTIONS 1.17"
uuid = "bdef76a3-0d85-4e3e-b5ad-6d166ad6d45a"
