[[commentary]]
quote='''
Compare this with 1 John [3:20]: "Dearly beloved, if our own hearts condemn us, God is greater than our conscience."
'''
source_url=''
source_title="AUGUSTINE ON ROMANS 10"
uuid = "f142616d-6436-4587-a50f-8b988bbee8d7"
