[[commentary]]
quote='''
This must not be understood in such a way as to say that a man who has received faith and continues to live is righteous, even though he leads a wicked life.
'''
source_url=''
source_title="QUESTIONS 76.1"
uuid = "eafafffd-bde8-4768-aa5b-cc01c109d67b"
