[[commentary]]
quote='''
God in himself is true; you in yourself are a liar—in him you can be true!
'''
source_url=''
source_title="HOMILIES ON JOHN 1.6"
uuid = "86d60f94-5596-4041-a643-8a516269299d"
