[[commentary]]
quote='''
Whenever Paul talks about the wrath of God he understands it to mean punishment.
'''
source_url=''
source_title="AUGUSTINE ON ROMANS 9"
uuid = "addc2cb2-7127-44ac-a36c-39bdb47ac15a"
