default_year=545
wiki='https://en.wikipedia.org/wiki/Barsanuphius'
uuid = "af4a6641-ceee-4437-bd15-2aec1e292430"
category = "Eastern & Byzantine Theology"
image = "https://download.biblians.com/commentaries/fathers/Barsanuphius_the_great.webp"
summary = "Barsanuphius, also known as Barsanuphius of Palestine, Barsanuphius of Gaza or Barsanuphius the Great, was a Christian hermit and writer of the sixth century. He is considered one of the Desert Fathers."
