[[commentary]]
quote='''
I believe the passage, "And my people shall see the glory of the Lord, and the majesty of God," refers to the presence of our Savior at the baptism, because it was there that the glory of the Savior was seen.
'''
source_url=''
source_title="PROOF OF THE GOSPEL 9:6"
uuid = "4870ce40-3710-4c62-a358-c8887d150354"
