[[commentary]]
quote='''
The Apostle Matthew, if you consider his former life, did not leave a holy occupation, but came from those consumed with tax-gathering and overreaching one another.
'''
source_url=''
source_title="PROOF OF THE GOSPEL 3.5"
uuid = "e31217ea-36e5-44de-913d-58c64849eabd"
