default_year=339
wiki='https://en.wikipedia.org/wiki/Eusebius'
uuid = "8512eed5-fb15-47df-906b-9b157e72063c"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/7/70/Eusebius_of_Caesarea_Rabbula_Gospels_Icon.jpg"
summary = "Eusebius of Caesarea, also known as Eusebius Pamphilius, was a historian of Christianity, exegete, and Christian polemicist from the Roman province of Syria Palaestina. In about AD 314 he became the bishop of Caesarea Palaestina."
