[[commentary]]
quote='''
Vain is the heart of the philosophers of alien ideas, about whom it is said, "The Lord knows the thoughts of the wise, that they are vain"; from their throats they spew out death-bearing dogmas as they teach the Word of God is not alive, and they bring forth lies and words of death.
'''
source_url=''
source_title="COMMENTARY ON PSALMS 5:10-11"
uuid = "00fa6ab1-3970-4b9a-a94f-2929d86cc8ad"
