[[commentary]]
quote='''
"face to face "and not "darkly "and "in part.".
Know that shadows and figures have ceased; and we hasten on to the truth, proclaiming its glorious images. For now we know "in part "and as it were "through a glass"
'''
uuid = "19d142d5-6cd5-436f-bdea-68dbcbfa5107"
