[[commentary]]
quote='''
That is, God, the Maker of all men; therefore, also, according to the apostle, He "will have all men to be saved, and to come unto the knowledge of the truth."
'''
uuid = "6c73c49a-a545-4ddc-b97a-c833f6fb942e"
