[[commentary]]
quote='''
Will receive our souls; so when this perishable life shall be dissolved, we shall have the habitation which is before the resurrection-that is, our souls shall he with God, until we shall receive the new house which is prepared for us, and which shall never fall. Whence also "we groan ""not for that we would be unclothed "as to the body, "but clothed upon"
'''
uuid = "4b2ee318-7419-463e-bff3-e1abec3e32b7"
