[[commentary]]
quote='''
Midnight stands for the reign of the antichrist, when the destroying angel will pass over the houses.
'''
source_url=''
source_title="BANQUET OF THE TEN VIRGINS 6.4"
uuid = "a11cb869-5f39-40a7-97f2-9f3d053e9eef"
