[[commentary]]
quote='''
They heard of the wine that, without previous culture, was ministered;
'''
source_url="http://ccel.org/fathers2/ANF-06/anf06-126.htm"
source_title="Methodius Oration on the Psalms"
uuid = "6af12bb3-34be-424f-aa8a-0b1301c34c01"
