[[commentary]]
quote='''
Here he says believers live; they never die. Their bodies die but are brought back to life again.
'''
source_url=''
source_title="ON THE RESURRECTION 3.21.6"
uuid = "af05d514-d67e-4b25-a7de-67175ac609fa"
