default_year=311
wiki='https://en.wikipedia.org/wiki/Methodius_of_Olympus'
uuid = "ec48e8f1-730f-483b-9a73-117885c2067d"
category = "Early Fathers"
image = "https://upload.wikimedia.org/wikipedia/commons/1/1f/Methodius_of_Olympus.jpg"
summary = "Methodius of Olympus was an early Christian bishop, ecclesiastical author, and martyr. Today, he is honored as a saint and Church Father; the Catholic Church commemorates his feast on June 20."
