[[commentary]]
quote='''
For thy light is come, and the glory of the Lord is risen upon thee. "Now these promises, it is evident to every one, will be fulfilled after the resurrection.
'''
uuid = "e1f3de69-8e0e-410f-9347-d563db0e818e"
