[[commentary]]
quote='''
Because it was given, not for injury, but for safety; for let us not suppose that God makes anything useless or hurtful. What thou? "Was then that which is good made death unto me? "
'''
uuid = "3299a7e6-eda2-4990-8d6f-a8702df98ccc"
