default_year=1295
wiki='https://en.wikipedia.org/wiki/Nicholas_of_Gorran'
uuid = "fbb359ab-5835-49ef-93af-db4bf622f6be"
category = "Western & Medieval Theology"
summary = "Nicholas of Gorran (1232–1295) was born in Gorron, France. He was a prominent French Roman Catholic medieval preacher and scriptural commentator."
