[[commentary]]
quote='''
Among holy men it is impossible not to fall into those small lapses which occur because of something said, some thought, some surreptitious act. These sins are quite different from those which are called mortal, but they are not without blame or reproach.
'''
source_url=''
source_title="CONFERENCE 11.9"
uuid = "01b2692c-b1e7-42a8-9fa6-989dc4151843"
