[[commentary]]
quote='''
We are thus taught by the words of the Lord himself: everything is granted to us by God, and that the whole of our salvation is to be ascribed not to the merit of our own works but to heavenly grace.
'''
source_url=''
source_title="CONFERENCE 13:18"
uuid = "ba94cea8-4f95-4db8-b9d2-c72aeec5b206"
