[[commentary]]
quote='''
How can we imagine without grievous blasphemy that he does not generally will all men, but only some instead of all to be saved?
'''
source_url=''
source_title="CONFERENCE 13:7"
uuid = "1dbc3dd2-0b19-421e-93eb-1bbba2dd82ed"
