[[commentary]]
quote='''
Be careful, for daily the devil considers you and gnashes his teeth over you; but [as it says in the next verse] the Lord mocks him because he knows his day will come.
'''
source_url=''
source_title="COMMENTARY ON THE PSALMS 37"
uuid = "023077ff-ff98-48b2-b03e-9e62cfa6ecff"
