[[commentary]]
quote='''
For one who errs by simplicity may be pardoned, as the blessed Apostle Paul says of himself, "I who at first was a blasphemer, and a persecutor, and injurious; yet obtained mercy, because I did it ignorantly."
'''
source_url="https://historicalchristian.faith/by_father.php?file=Cyprian%2FLetters%2FEpistle%252072.html"
source_title="Epistle LXXII"
uuid = "5ab130a8-cd05-42cf-adc8-d03bbb7c9e60"
