[[commentary]]
quote='''
"They went to the prophet Huldah," and not to Jeremiah, even though he was already well known as a prophet, probably because Jeremiah was not there at the moment, or maybe because this woman surpassed him with the power of her gift of prophecy.
'''
source_url=''
source_title="BOOKS OF SESSIONS 2 KINGS 22:14"
uuid = "fe017a9d-09a4-4e40-9374-9786b6472e09"
