[[commentary]]
quote='''
"Out of the earth still others will spring." In other words, God inflicts these punishments on the impious as their just reward, but with regard to the righteous, regardless of the state of abasement in which he finds them, God will make them spring up again, rendering them glorious.
'''
source_url=''
source_title="COMMENTARY ON JOB 8:19"
uuid = "cc9f8701-ac6d-4e10-9896-04a036a160ce"
