[[commentary]]
quote='''
The author seems to say that Job's friends will abstain from pronouncing reproaches, because of the fear of God and the terror that he inspires.
'''
source_url=''
source_title="COMMENTARY ON JOB 13:11"
uuid = "dba89ff7-46d1-43c0-8fb1-7a4bdd08f3a2"
