[[commentary]]
quote='''
"My eye will begin to see good again." Here the author refers to the hope that is reserved for people in the new world.
'''
source_url=''
source_title="COMMENTARY ON JOB 7:7"
uuid = "7d3afcb9-9271-43dd-95b7-a7c9c7cd49f4"
