[[commentary]]
quote='''
These words mean, "You imitate the actions of the ancestors." [The author] is alluding to the Cainites, those who lived at the time of the deluge, to the Sodomites, etc.; these are those whom he calls "the way of the world."
'''
source_url=''
source_title="COMMENTARY ON JOB 22:15"
uuid = "5d8f8f50-1278-46cd-943e-6c222592e00c"
