[[commentary]]
quote='''
"He will drink iniquity like water." The author says these words in order to show that [human beings] enjoy uttering blasphemies.
'''
source_url=''
source_title="COMMENTARY ON JOB 15:16"
uuid = "41de4865-c8e9-4fb1-a948-f7a9c4a13344"
