[[commentary]]
quote='''
That the women were to see his resurrection, while the scribes and Pharisees and the people disbelieved, this also Isaiah foretold in these words, "You women, who come from beholding, come: for it is a people that has no understanding."
'''
source_url=''
source_title="COMMENTARY ON THE APOSTLES' CREED 30"
uuid = "2e64dd49-e524-4b98-a4ba-23c9d97b006b"
