[[commentary]]
quote='''
Look what the apostle Peter has to say about Christians who live in the mire and impurities of this world.
'''
source_url=''
source_title="ON THE GOVERNANCE OF GOD 4.19"
uuid = "81ac85c4-d3a8-4765-a92f-bf7dacf9b1f5"
