[[commentary]]
quote='''
What is a holy appellation without merit but an ornament set in the mud? The holy Scriptures have testified to this in writing: "A golden ring in a swine's snout, a woman fair and foolish." And in us the appellation Christian is like a golden ornament. If we use it unworthily, we seem to be swine with an ornament.
'''
source_url=''
source_title="THE GOVERNANCE OF GOD 4:1"
uuid = "0f0ebbc3-93dc-4ee6-845e-c2bb300c9c34"
