[[commentary]]
quote='''
For as the bread and wine of the Eucharist before the holy invocation of the adorable Trinity were ordinary bread and wine, while after the invocation the bread becomes the body of Christ and the wine becomes his blood, so these foods of the pomp of Satan, though of their own nature ordinary food, become profane through the invocation of evil spirits.
'''
source_url=''
source_title="MYSTAGOGICAL LECTURE 1.7"
uuid = "0cb38d0b-6aaf-4e80-89ff-e268c3dc248a"
