[[commentary]]
quote='''
When Christ's body and blood become the tissue of our members, we become Christ-bearers and "partakers of the divine nature," as the blessed Peter said.
'''
source_url=''
source_title="MYSTAGOGICAL LECTURES 4.3"
uuid = "4e75fd3b-4d86-400b-ad4c-1578384b4264"
