default_year=386
wiki='https://en.wikipedia.org/wiki/Cyril_of_Jerusalem'
uuid = "35d1f873-113a-4bd3-b9d5-514d32b815c6"
category = "Eastern & Byzantine Theology"
image = "https://upload.wikimedia.org/wikipedia/commons/6/69/Saint_Cyril_of_Jerusalem.jpg"
summary = "Cyril of Jerusalem was a theologian of the Early Church. About the end of AD 350, he succeeded Maximus as Bishop of Jerusalem, but was exiled on more than one occasion due to the enmity of Acacius of Caesarea, and the policies of various emperors. Cyril left important writings documenting the instruction of catechumens and the order of the Liturgy in his day and his old age"
