[[commentary]]
quote='''
If Phinehas by his zeal in slaying the evildoer appeased the wrath of God, shall not Jesus, who slew no other but "gave himself a ransom for all," take away God's wrath against humanity?
'''
source_url='https://www.newadvent.org/fathers/310101.htm'
source_title="Catechetical Lecture 13.2"
uuid = "76e13859-dfa6-4cfd-9314-3145b9b6277a"
