[[commentary]]
quote='''
This Tyre also lay waste seventy years like Jerusalem, which sat in desolation seventy years.
'''
source_url=''
source_title="DEMONSTRATION 5:9"
uuid = "5a551089-5515-49a4-a4b2-36fd4c90e8cc"
