[[commentary]]
quote='''
When someone sweeps clean their soul in the name of Christ, Christ dwells in them and God dwells in Christ. From that time onward, that person becomes one of three persons—himself; Christ, who dwells in him; and God, who dwells in Christ.
'''
source_url=''
source_title="DEMONSTRATION 4.11"
uuid = "63046f46-b67f-412a-aaba-556afd3ecc1d"
