default_year=455
wiki='https://en.wikipedia.org/wiki/Prosper_of_Aquitaine'
uuid = "9b122919-d8dd-4bbc-a39c-9f1881dd37fc"
category = "Western & Medieval Theology"
image = "https://download.biblians.com/commentaries/fathers/Aquitániai_Szent_Prosper.webp"
summary = "Prosper of Aquitaine, also called Prosper Tiro, was a Christian writer and disciple of Augustine of Hippo, and the first continuator of Jerome's Universal Chronicle. Particularly, Prosper is identified with the (later) axiom 'lex orandi, lex credendi, lex vivendi'—'the law [or those things] we pray is the law we believe is the law we live."
