default_year=1171
wiki='https://en.wikipedia.org/wiki/Dionysius_bar_Salibi'
uuid = "65fb1961-3c68-4a8e-97b6-91ed566d9435"
category = "Syriac & Oriental Theology"
summary = "Dionysius bar Salibi was a Syriac Orthodox writer and bishop, who served as metropolitan of Amid, in Upper Mesopotamia, from 1166 to 1171. He was one of the most prominent and prolific writers within the Syriac Orthodox Church during the twelfth century."
