default_year=1889
wiki='https://en.wikipedia.org/wiki/J._B._Lightfoot'
uuid = "e9b20268-7064-4802-8da0-4e8a8280b77f"
category = "Reformation & Modern"
image = "https://download.biblians.com/commentaries/fathers/Joseph-barber-lightfoot.webp"
summary = "Joseph Barber Lightfoot, known as J. B. Lightfoot, was an English Anglican theologian and Bishop of Durham."
