default_year=56
wiki='https://en.wikipedia.org/wiki/Second_Epistle_to_the_Corinthians'
uuid = "c844741a-4c35-4ba9-a8f9-aab06948c558"
category = "Canonical Scriptures"
image = "https://download.biblians.com/commentaries/fathers/Ann_Arbor,_University_of_Michigan_P.Mich.inv._6238_(Papyrus_46)_fol._142r_-_2_Corinthians_11,33-12,9.webp"
summary = "The Second Epistle to the Corinthians is a Pauline epistle of the New Testament of the Christian Bible. The epistle is attributed to Paul the Apostle and a co-author named Timothy, and is addressed to the church in Corinth and Christians in the surrounding province of Achaea, in modern-day Greece. According to Jerome, Titus was the amanuensis of this epistle."
