[[commentary]]
quote='''
Of the incorporeal beings, only angels fell away, and not all of them, but some only, that inclined to things below and set their desire on things of earth, withdrawing themselves from their relations with things above, even from God.
'''
source_url=''
source_title="ON THE NATURE OF MAN 58"
uuid = "6ebc98d1-9767-4c2b-9c47-c3ef322e3db4"
