default_year=437
wiki='https://en.wikipedia.org//wiki/Possidius'
uuid = "127fccb7-a9ce-4565-9c40-537f97c343f6"
category = "Western & Medieval Theology"
summary = "Possidius was a friend of Augustine of Hippo who wrote a biography and an indiculus or list of his works. He was bishop of Calama in the Roman province of Numidia."
